
// This file has been generated by the GUI designer. Do not modify.
namespace Momiji
{
	public partial class frmAuctionSale
	{
		private global::Gtk.HBox hboxCheckin;
		private global::Gtk.ScrolledWindow GtkScrolWinMerch;
		private global::Gtk.NodeView lstMerch;
		private global::Gtk.VBox vbox2;
		private global::Gtk.Label lblBarcode;
		private global::Gtk.Entry txtBarcode;
		private global::Gtk.Label lblPrice;
		private global::Gtk.Entry txtPrice;
		private global::Gtk.HBox hbox1;
		private global::Gtk.Button btnAddToList;
		private global::Gtk.Button btnClear;
		private global::Gtk.Table table1;
		private global::Gtk.Label lblPaid;
		private global::Gtk.Label lblTotal;
		private global::Gtk.Entry txtPaid;
		private global::Gtk.Entry txtTotal;
		private global::Gtk.Button btnPay;
		private global::Gtk.HBox hbox3;
		private global::Gtk.Label lblChange;
		private global::Gtk.Entry txtChange;
		private global::Gtk.Button btnCancel;
		
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget Momiji.frmAuctionSale
			this.WidthRequest = 800;
			this.Name = "Momiji.frmAuctionSale";
			this.Title = global::Mono.Unix.Catalog.GetString ("frmAuctionSale");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child Momiji.frmAuctionSale.Gtk.Container+ContainerChild
			this.hboxCheckin = new global::Gtk.HBox ();
			this.hboxCheckin.Name = "hboxCheckin";
			this.hboxCheckin.Spacing = 6;
			// Container child hboxCheckin.Gtk.Box+BoxChild
			this.GtkScrolWinMerch = new global::Gtk.ScrolledWindow ();
			this.GtkScrolWinMerch.Name = "GtkScrolWinMerch";
			this.GtkScrolWinMerch.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolWinMerch.Gtk.Container+ContainerChild
			this.lstMerch = new global::Gtk.NodeView ();
			this.lstMerch.CanFocus = true;
			this.lstMerch.Name = "lstMerch";
			this.lstMerch.EnableSearch = false;
			this.GtkScrolWinMerch.Add (this.lstMerch);
			this.hboxCheckin.Add (this.GtkScrolWinMerch);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hboxCheckin [this.GtkScrolWinMerch]));
			w2.Position = 0;
			// Container child hboxCheckin.Gtk.Box+BoxChild
			this.vbox2 = new global::Gtk.VBox ();
			this.vbox2.Name = "vbox2";
			this.vbox2.Spacing = 6;
			this.vbox2.BorderWidth = ((uint)(8));
			// Container child vbox2.Gtk.Box+BoxChild
			this.lblBarcode = new global::Gtk.Label ();
			this.lblBarcode.Name = "lblBarcode";
			this.lblBarcode.Xalign = 0F;
			this.lblBarcode.LabelProp = global::Mono.Unix.Catalog.GetString ("Highlight this box and scan:");
			this.vbox2.Add (this.lblBarcode);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.lblBarcode]));
			w3.Position = 0;
			w3.Expand = false;
			w3.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.txtBarcode = new global::Gtk.Entry ();
			this.txtBarcode.CanFocus = true;
			this.txtBarcode.Name = "txtBarcode";
			this.txtBarcode.IsEditable = true;
			this.txtBarcode.InvisibleChar = '●';
			this.vbox2.Add (this.txtBarcode);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.txtBarcode]));
			w4.Position = 1;
			w4.Expand = false;
			w4.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.lblPrice = new global::Gtk.Label ();
			this.lblPrice.Name = "lblPrice";
			this.lblPrice.Xalign = 0F;
			this.lblPrice.LabelProp = global::Mono.Unix.Catalog.GetString ("Price item sold for:");
			this.vbox2.Add (this.lblPrice);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.lblPrice]));
			w5.Position = 2;
			w5.Expand = false;
			w5.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.txtPrice = new global::Gtk.Entry ();
			this.txtPrice.CanFocus = true;
			this.txtPrice.Name = "txtPrice";
			this.txtPrice.IsEditable = true;
			this.txtPrice.InvisibleChar = '●';
			this.vbox2.Add (this.txtPrice);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.txtPrice]));
			w6.Position = 3;
			w6.Expand = false;
			w6.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.hbox1 = new global::Gtk.HBox ();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.btnAddToList = new global::Gtk.Button ();
			this.btnAddToList.CanFocus = true;
			this.btnAddToList.Name = "btnAddToList";
			this.btnAddToList.UseUnderline = true;
			// Container child btnAddToList.Gtk.Container+ContainerChild
			global::Gtk.Alignment w7 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w8 = new global::Gtk.HBox ();
			w8.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w9 = new global::Gtk.Image ();
			w9.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-add", global::Gtk.IconSize.Menu);
			w8.Add (w9);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w11 = new global::Gtk.Label ();
			w11.LabelProp = global::Mono.Unix.Catalog.GetString ("Add to list");
			w11.UseUnderline = true;
			w8.Add (w11);
			w7.Add (w8);
			this.btnAddToList.Add (w7);
			this.hbox1.Add (this.btnAddToList);
			global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.btnAddToList]));
			w15.Position = 0;
			w15.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.btnClear = new global::Gtk.Button ();
			this.btnClear.CanFocus = true;
			this.btnClear.Name = "btnClear";
			this.btnClear.UseUnderline = true;
			// Container child btnClear.Gtk.Container+ContainerChild
			global::Gtk.Alignment w16 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w17 = new global::Gtk.HBox ();
			w17.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w18 = new global::Gtk.Image ();
			w18.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-delete", global::Gtk.IconSize.Menu);
			w17.Add (w18);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w20 = new global::Gtk.Label ();
			w20.LabelProp = global::Mono.Unix.Catalog.GetString ("Clear");
			w20.UseUnderline = true;
			w17.Add (w20);
			w16.Add (w17);
			this.btnClear.Add (w16);
			this.hbox1.Add (this.btnClear);
			global::Gtk.Box.BoxChild w24 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.btnClear]));
			w24.Position = 1;
			w24.Fill = false;
			this.vbox2.Add (this.hbox1);
			global::Gtk.Box.BoxChild w25 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.hbox1]));
			w25.Position = 4;
			w25.Expand = false;
			w25.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.table1 = new global::Gtk.Table (((uint)(2)), ((uint)(2)), false);
			this.table1.Name = "table1";
			this.table1.RowSpacing = ((uint)(6));
			this.table1.ColumnSpacing = ((uint)(6));
			// Container child table1.Gtk.Table+TableChild
			this.lblPaid = new global::Gtk.Label ();
			this.lblPaid.Name = "lblPaid";
			this.lblPaid.Xalign = 0F;
			this.lblPaid.LabelProp = global::Mono.Unix.Catalog.GetString ("Paid: <b>$</b>");
			this.lblPaid.UseMarkup = true;
			this.table1.Add (this.lblPaid);
			global::Gtk.Table.TableChild w26 = ((global::Gtk.Table.TableChild)(this.table1 [this.lblPaid]));
			w26.TopAttach = ((uint)(1));
			w26.BottomAttach = ((uint)(2));
			w26.XOptions = ((global::Gtk.AttachOptions)(4));
			w26.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.lblTotal = new global::Gtk.Label ();
			this.lblTotal.Name = "lblTotal";
			this.lblTotal.LabelProp = global::Mono.Unix.Catalog.GetString ("Total: <b>$</b>");
			this.lblTotal.UseMarkup = true;
			this.table1.Add (this.lblTotal);
			global::Gtk.Table.TableChild w27 = ((global::Gtk.Table.TableChild)(this.table1 [this.lblTotal]));
			w27.XOptions = ((global::Gtk.AttachOptions)(4));
			w27.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.txtPaid = new global::Gtk.Entry ();
			this.txtPaid.CanFocus = true;
			this.txtPaid.Name = "txtPaid";
			this.txtPaid.IsEditable = true;
			this.txtPaid.InvisibleChar = '●';
			this.table1.Add (this.txtPaid);
			global::Gtk.Table.TableChild w28 = ((global::Gtk.Table.TableChild)(this.table1 [this.txtPaid]));
			w28.TopAttach = ((uint)(1));
			w28.BottomAttach = ((uint)(2));
			w28.LeftAttach = ((uint)(1));
			w28.RightAttach = ((uint)(2));
			w28.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.txtTotal = new global::Gtk.Entry ();
			this.txtTotal.Sensitive = false;
			this.txtTotal.CanFocus = true;
			this.txtTotal.Name = "txtTotal";
			this.txtTotal.IsEditable = true;
			this.txtTotal.InvisibleChar = '●';
			this.table1.Add (this.txtTotal);
			global::Gtk.Table.TableChild w29 = ((global::Gtk.Table.TableChild)(this.table1 [this.txtTotal]));
			w29.LeftAttach = ((uint)(1));
			w29.RightAttach = ((uint)(2));
			w29.YOptions = ((global::Gtk.AttachOptions)(4));
			this.vbox2.Add (this.table1);
			global::Gtk.Box.BoxChild w30 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.table1]));
			w30.Position = 5;
			w30.Expand = false;
			w30.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.btnPay = new global::Gtk.Button ();
			this.btnPay.CanFocus = true;
			this.btnPay.Name = "btnPay";
			this.btnPay.UseUnderline = true;
			// Container child btnPay.Gtk.Container+ContainerChild
			global::Gtk.Alignment w31 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w32 = new global::Gtk.HBox ();
			w32.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w33 = new global::Gtk.Image ();
			w33.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("Momiji.Resources.shopping-bag-icon.png");
			w32.Add (w33);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w35 = new global::Gtk.Label ();
			w35.LabelProp = global::Mono.Unix.Catalog.GetString ("Mark as Paid");
			w35.UseUnderline = true;
			w32.Add (w35);
			w31.Add (w32);
			this.btnPay.Add (w31);
			this.vbox2.Add (this.btnPay);
			global::Gtk.Box.BoxChild w39 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.btnPay]));
			w39.Position = 6;
			w39.Expand = false;
			w39.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.hbox3 = new global::Gtk.HBox ();
			this.hbox3.Name = "hbox3";
			this.hbox3.Spacing = 6;
			// Container child hbox3.Gtk.Box+BoxChild
			this.lblChange = new global::Gtk.Label ();
			this.lblChange.Name = "lblChange";
			this.lblChange.LabelProp = global::Mono.Unix.Catalog.GetString ("Change: <b>$</b>");
			this.lblChange.UseMarkup = true;
			this.hbox3.Add (this.lblChange);
			global::Gtk.Box.BoxChild w40 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.lblChange]));
			w40.Position = 0;
			w40.Expand = false;
			w40.Fill = false;
			// Container child hbox3.Gtk.Box+BoxChild
			this.txtChange = new global::Gtk.Entry ();
			this.txtChange.Sensitive = false;
			this.txtChange.CanFocus = true;
			this.txtChange.Name = "txtChange";
			this.txtChange.IsEditable = false;
			this.txtChange.InvisibleChar = '●';
			this.hbox3.Add (this.txtChange);
			global::Gtk.Box.BoxChild w41 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.txtChange]));
			w41.Position = 1;
			this.vbox2.Add (this.hbox3);
			global::Gtk.Box.BoxChild w42 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.hbox3]));
			w42.Position = 7;
			w42.Expand = false;
			w42.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.btnCancel = new global::Gtk.Button ();
			this.btnCancel.CanFocus = true;
			this.btnCancel.Name = "btnCancel";
			this.btnCancel.UseUnderline = true;
			// Container child btnCancel.Gtk.Container+ContainerChild
			global::Gtk.Alignment w43 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w44 = new global::Gtk.HBox ();
			w44.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w45 = new global::Gtk.Image ();
			w45.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-cancel", global::Gtk.IconSize.Menu);
			w44.Add (w45);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w47 = new global::Gtk.Label ();
			w47.LabelProp = global::Mono.Unix.Catalog.GetString ("Clear Transaction");
			w47.UseUnderline = true;
			w44.Add (w47);
			w43.Add (w44);
			this.btnCancel.Add (w43);
			this.vbox2.Add (this.btnCancel);
			global::Gtk.Box.BoxChild w51 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.btnCancel]));
			w51.Position = 8;
			w51.Expand = false;
			w51.Fill = false;
			w51.Padding = ((uint)(8));
			this.hboxCheckin.Add (this.vbox2);
			global::Gtk.Box.BoxChild w52 = ((global::Gtk.Box.BoxChild)(this.hboxCheckin [this.vbox2]));
			w52.Position = 1;
			w52.Expand = false;
			w52.Fill = false;
			w52.Padding = ((uint)(8));
			this.Add (this.hboxCheckin);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 800;
			this.DefaultHeight = 435;
			this.Show ();
			this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
			this.txtBarcode.Activated += new global::System.EventHandler (this.OnTxtBarcodeActivated);
			this.txtPrice.Activated += new global::System.EventHandler (this.OnTxtPriceActivated);
			this.btnAddToList.Clicked += new global::System.EventHandler (this.OnBtnAddToListClicked);
			this.btnClear.Clicked += new global::System.EventHandler (this.OnBtnClearClicked);
			this.txtPaid.Activated += new global::System.EventHandler (this.OnTxtPaidActivated);
			this.btnPay.Clicked += new global::System.EventHandler (this.OnBtnPayClicked);
			this.btnCancel.Clicked += new global::System.EventHandler (this.OnBtnCancelClicked);
		}
	}
}
