
// This file has been generated by the GUI designer. Do not modify.
namespace Momiji
{
	public partial class frmPricing
	{
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget Momiji.frmPricing
			this.Name = "Momiji.frmPricing";
			this.Title = global::Mono.Unix.Catalog.GetString ("frmPricing");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 400;
			this.DefaultHeight = 300;
			this.Show ();
		}
	}
}
