
// This file has been generated by the GUI designer. Do not modify.
namespace Momiji
{
	public partial class frmReceipts
	{
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget Momiji.frmReceipts
			this.Name = "Momiji.frmReceipts";
			this.Title = global::Mono.Unix.Catalog.GetString ("frmReceipts");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 400;
			this.DefaultHeight = 300;
			this.Show ();
		}
	}
}
