
// This file has been generated by the GUI designer. Do not modify.
namespace Momiji
{
	public partial class frmUserEdit
	{
		private global::Gtk.VBox vboxUser;
		private global::Gtk.Label lblChooseUser;
		private global::Gtk.ComboBox drpUsers;
		private global::Gtk.HBox hboxActions;
		private global::Gtk.Button btnDelete;
		private global::Gtk.Frame frmUserInfo;
		private global::Gtk.Alignment GtkAlignment2;
		private global::Gtk.VBox vboxUserInfo;
		private global::Gtk.Label lblUsername;
		private global::Gtk.Entry txtUsername;
		private global::Gtk.Label lblName;
		private global::Gtk.Entry txtName;
		private global::Gtk.Label lblRank;
		private global::Gtk.ComboBox drpRank;
		private global::Gtk.Table tblPass;
		private global::Gtk.Label lblPass;
		private global::Gtk.Label lblPassRepeat;
		private global::Gtk.Entry txtPass;
		private global::Gtk.Entry txtPassRepeat;
		private global::Gtk.Label UserInfo;
		private global::Gtk.HBox hboxUpdateCancel;
		private global::Gtk.Button btnClose;
		private global::Gtk.Alignment alignment2;
		private global::Gtk.Button btnCancel;
		private global::Gtk.Button btnUpdate;
		
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget Momiji.frmUserEdit
			this.Name = "Momiji.frmUserEdit";
			this.Title = global::Mono.Unix.Catalog.GetString ("Edit User");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			this.Modal = true;
			this.BorderWidth = ((uint)(8));
			// Container child Momiji.frmUserEdit.Gtk.Container+ContainerChild
			this.vboxUser = new global::Gtk.VBox ();
			this.vboxUser.Name = "vboxUser";
			this.vboxUser.Spacing = 6;
			this.vboxUser.BorderWidth = ((uint)(16));
			// Container child vboxUser.Gtk.Box+BoxChild
			this.lblChooseUser = new global::Gtk.Label ();
			this.lblChooseUser.Name = "lblChooseUser";
			this.lblChooseUser.Xalign = 0F;
			this.lblChooseUser.LabelProp = global::Mono.Unix.Catalog.GetString ("Choose a user:");
			this.vboxUser.Add (this.lblChooseUser);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vboxUser [this.lblChooseUser]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			// Container child vboxUser.Gtk.Box+BoxChild
			this.drpUsers = global::Gtk.ComboBox.NewText ();
			this.drpUsers.Name = "drpUsers";
			this.vboxUser.Add (this.drpUsers);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vboxUser [this.drpUsers]));
			w2.Position = 1;
			w2.Expand = false;
			w2.Fill = false;
			// Container child vboxUser.Gtk.Box+BoxChild
			this.hboxActions = new global::Gtk.HBox ();
			this.hboxActions.Name = "hboxActions";
			this.hboxActions.Spacing = 6;
			// Container child hboxActions.Gtk.Box+BoxChild
			this.btnDelete = new global::Gtk.Button ();
			this.btnDelete.CanFocus = true;
			this.btnDelete.Name = "btnDelete";
			this.btnDelete.UseUnderline = true;
			// Container child btnDelete.Gtk.Container+ContainerChild
			global::Gtk.Alignment w3 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w4 = new global::Gtk.HBox ();
			w4.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w5 = new global::Gtk.Image ();
			w5.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-delete", global::Gtk.IconSize.Menu);
			w4.Add (w5);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w7 = new global::Gtk.Label ();
			w7.LabelProp = global::Mono.Unix.Catalog.GetString ("Delete");
			w7.UseUnderline = true;
			w4.Add (w7);
			w3.Add (w4);
			this.btnDelete.Add (w3);
			this.hboxActions.Add (this.btnDelete);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.hboxActions [this.btnDelete]));
			w11.Position = 0;
			w11.Expand = false;
			w11.Fill = false;
			this.vboxUser.Add (this.hboxActions);
			global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.vboxUser [this.hboxActions]));
			w12.Position = 2;
			w12.Expand = false;
			w12.Fill = false;
			// Container child vboxUser.Gtk.Box+BoxChild
			this.frmUserInfo = new global::Gtk.Frame ();
			this.frmUserInfo.Name = "frmUserInfo";
			this.frmUserInfo.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child frmUserInfo.Gtk.Container+ContainerChild
			this.GtkAlignment2 = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
			this.GtkAlignment2.Name = "GtkAlignment2";
			this.GtkAlignment2.LeftPadding = ((uint)(12));
			this.GtkAlignment2.BorderWidth = ((uint)(8));
			// Container child GtkAlignment2.Gtk.Container+ContainerChild
			this.vboxUserInfo = new global::Gtk.VBox ();
			this.vboxUserInfo.Name = "vboxUserInfo";
			this.vboxUserInfo.Spacing = 6;
			// Container child vboxUserInfo.Gtk.Box+BoxChild
			this.lblUsername = new global::Gtk.Label ();
			this.lblUsername.Name = "lblUsername";
			this.lblUsername.Xalign = 0F;
			this.lblUsername.LabelProp = global::Mono.Unix.Catalog.GetString ("Username:");
			this.vboxUserInfo.Add (this.lblUsername);
			global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.vboxUserInfo [this.lblUsername]));
			w13.Position = 0;
			w13.Expand = false;
			w13.Fill = false;
			// Container child vboxUserInfo.Gtk.Box+BoxChild
			this.txtUsername = new global::Gtk.Entry ();
			this.txtUsername.CanFocus = true;
			this.txtUsername.Name = "txtUsername";
			this.txtUsername.IsEditable = true;
			this.txtUsername.InvisibleChar = '●';
			this.vboxUserInfo.Add (this.txtUsername);
			global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.vboxUserInfo [this.txtUsername]));
			w14.Position = 1;
			w14.Expand = false;
			w14.Fill = false;
			// Container child vboxUserInfo.Gtk.Box+BoxChild
			this.lblName = new global::Gtk.Label ();
			this.lblName.Name = "lblName";
			this.lblName.Xalign = 0F;
			this.lblName.LabelProp = global::Mono.Unix.Catalog.GetString ("First and Lastname:");
			this.vboxUserInfo.Add (this.lblName);
			global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.vboxUserInfo [this.lblName]));
			w15.Position = 2;
			w15.Expand = false;
			w15.Fill = false;
			// Container child vboxUserInfo.Gtk.Box+BoxChild
			this.txtName = new global::Gtk.Entry ();
			this.txtName.CanFocus = true;
			this.txtName.Name = "txtName";
			this.txtName.IsEditable = true;
			this.txtName.InvisibleChar = '●';
			this.vboxUserInfo.Add (this.txtName);
			global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.vboxUserInfo [this.txtName]));
			w16.Position = 3;
			w16.Expand = false;
			w16.Fill = false;
			// Container child vboxUserInfo.Gtk.Box+BoxChild
			this.lblRank = new global::Gtk.Label ();
			this.lblRank.Name = "lblRank";
			this.lblRank.Xalign = 0F;
			this.lblRank.LabelProp = global::Mono.Unix.Catalog.GetString ("Rank:");
			this.vboxUserInfo.Add (this.lblRank);
			global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.vboxUserInfo [this.lblRank]));
			w17.Position = 4;
			w17.Expand = false;
			w17.Fill = false;
			// Container child vboxUserInfo.Gtk.Box+BoxChild
			this.drpRank = global::Gtk.ComboBox.NewText ();
			this.drpRank.AppendText (global::Mono.Unix.Catalog.GetString ("0 - Login"));
			this.drpRank.AppendText (global::Mono.Unix.Catalog.GetString ("1 - Gallery Store Sales"));
			this.drpRank.AppendText (global::Mono.Unix.Catalog.GetString ("2 - Quick Sales"));
			this.drpRank.AppendText (global::Mono.Unix.Catalog.GetString ("3 - Auction Sales"));
			this.drpRank.AppendText (global::Mono.Unix.Catalog.GetString ("4 - Re-Print Receipts"));
			this.drpRank.AppendText (global::Mono.Unix.Catalog.GetString ("5 - Check-in Artists"));
			this.drpRank.AppendText (global::Mono.Unix.Catalog.GetString ("6 - Bidding sheets, Check-out, Bidders"));
			this.drpRank.AppendText (global::Mono.Unix.Catalog.GetString ("7 - Manage artist stock"));
			this.drpRank.AppendText (global::Mono.Unix.Catalog.GetString ("8 - View Activity logs"));
			this.drpRank.AppendText (global::Mono.Unix.Catalog.GetString ("9 - View Monetary activity logs"));
			this.drpRank.AppendText (global::Mono.Unix.Catalog.GetString ("10 - Manage Treasury/refunds"));
			this.drpRank.AppendText (global::Mono.Unix.Catalog.GetString ("11 - Administrator"));
			this.drpRank.Name = "drpRank";
			this.vboxUserInfo.Add (this.drpRank);
			global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.vboxUserInfo [this.drpRank]));
			w18.Position = 5;
			w18.Expand = false;
			w18.Fill = false;
			// Container child vboxUserInfo.Gtk.Box+BoxChild
			this.tblPass = new global::Gtk.Table (((uint)(2)), ((uint)(2)), false);
			this.tblPass.Name = "tblPass";
			this.tblPass.RowSpacing = ((uint)(6));
			this.tblPass.ColumnSpacing = ((uint)(6));
			// Container child tblPass.Gtk.Table+TableChild
			this.lblPass = new global::Gtk.Label ();
			this.lblPass.Name = "lblPass";
			this.lblPass.Xalign = 0F;
			this.lblPass.LabelProp = global::Mono.Unix.Catalog.GetString ("Password");
			this.tblPass.Add (this.lblPass);
			global::Gtk.Table.TableChild w19 = ((global::Gtk.Table.TableChild)(this.tblPass [this.lblPass]));
			w19.XOptions = ((global::Gtk.AttachOptions)(4));
			w19.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tblPass.Gtk.Table+TableChild
			this.lblPassRepeat = new global::Gtk.Label ();
			this.lblPassRepeat.Name = "lblPassRepeat";
			this.lblPassRepeat.Xalign = 0F;
			this.lblPassRepeat.LabelProp = global::Mono.Unix.Catalog.GetString ("Retype Password:");
			this.tblPass.Add (this.lblPassRepeat);
			global::Gtk.Table.TableChild w20 = ((global::Gtk.Table.TableChild)(this.tblPass [this.lblPassRepeat]));
			w20.LeftAttach = ((uint)(1));
			w20.RightAttach = ((uint)(2));
			w20.XOptions = ((global::Gtk.AttachOptions)(4));
			w20.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tblPass.Gtk.Table+TableChild
			this.txtPass = new global::Gtk.Entry ();
			this.txtPass.CanFocus = true;
			this.txtPass.Name = "txtPass";
			this.txtPass.IsEditable = true;
			this.txtPass.InvisibleChar = '●';
			this.tblPass.Add (this.txtPass);
			global::Gtk.Table.TableChild w21 = ((global::Gtk.Table.TableChild)(this.tblPass [this.txtPass]));
			w21.TopAttach = ((uint)(1));
			w21.BottomAttach = ((uint)(2));
			w21.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tblPass.Gtk.Table+TableChild
			this.txtPassRepeat = new global::Gtk.Entry ();
			this.txtPassRepeat.CanFocus = true;
			this.txtPassRepeat.Name = "txtPassRepeat";
			this.txtPassRepeat.IsEditable = true;
			this.txtPassRepeat.InvisibleChar = '●';
			this.tblPass.Add (this.txtPassRepeat);
			global::Gtk.Table.TableChild w22 = ((global::Gtk.Table.TableChild)(this.tblPass [this.txtPassRepeat]));
			w22.TopAttach = ((uint)(1));
			w22.BottomAttach = ((uint)(2));
			w22.LeftAttach = ((uint)(1));
			w22.RightAttach = ((uint)(2));
			w22.YOptions = ((global::Gtk.AttachOptions)(4));
			this.vboxUserInfo.Add (this.tblPass);
			global::Gtk.Box.BoxChild w23 = ((global::Gtk.Box.BoxChild)(this.vboxUserInfo [this.tblPass]));
			w23.Position = 6;
			w23.Expand = false;
			w23.Fill = false;
			this.GtkAlignment2.Add (this.vboxUserInfo);
			this.frmUserInfo.Add (this.GtkAlignment2);
			this.UserInfo = new global::Gtk.Label ();
			this.UserInfo.Name = "UserInfo";
			this.UserInfo.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>User Info</b>");
			this.UserInfo.UseMarkup = true;
			this.frmUserInfo.LabelWidget = this.UserInfo;
			this.vboxUser.Add (this.frmUserInfo);
			global::Gtk.Box.BoxChild w26 = ((global::Gtk.Box.BoxChild)(this.vboxUser [this.frmUserInfo]));
			w26.Position = 3;
			w26.Expand = false;
			w26.Fill = false;
			// Container child vboxUser.Gtk.Box+BoxChild
			this.hboxUpdateCancel = new global::Gtk.HBox ();
			this.hboxUpdateCancel.Name = "hboxUpdateCancel";
			this.hboxUpdateCancel.Spacing = 6;
			// Container child hboxUpdateCancel.Gtk.Box+BoxChild
			this.btnClose = new global::Gtk.Button ();
			this.btnClose.CanFocus = true;
			this.btnClose.Name = "btnClose";
			this.btnClose.UseUnderline = true;
			// Container child btnClose.Gtk.Container+ContainerChild
			global::Gtk.Alignment w27 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w28 = new global::Gtk.HBox ();
			w28.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w29 = new global::Gtk.Image ();
			w29.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-close", global::Gtk.IconSize.Menu);
			w28.Add (w29);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w31 = new global::Gtk.Label ();
			w31.LabelProp = global::Mono.Unix.Catalog.GetString ("Close");
			w31.UseUnderline = true;
			w28.Add (w31);
			w27.Add (w28);
			this.btnClose.Add (w27);
			this.hboxUpdateCancel.Add (this.btnClose);
			global::Gtk.Box.BoxChild w35 = ((global::Gtk.Box.BoxChild)(this.hboxUpdateCancel [this.btnClose]));
			w35.Position = 0;
			w35.Expand = false;
			w35.Fill = false;
			// Container child hboxUpdateCancel.Gtk.Box+BoxChild
			this.alignment2 = new global::Gtk.Alignment (0.5F, 0.5F, 1F, 1F);
			this.alignment2.Name = "alignment2";
			this.hboxUpdateCancel.Add (this.alignment2);
			global::Gtk.Box.BoxChild w36 = ((global::Gtk.Box.BoxChild)(this.hboxUpdateCancel [this.alignment2]));
			w36.Position = 1;
			// Container child hboxUpdateCancel.Gtk.Box+BoxChild
			this.btnCancel = new global::Gtk.Button ();
			this.btnCancel.CanFocus = true;
			this.btnCancel.Name = "btnCancel";
			this.btnCancel.UseUnderline = true;
			// Container child btnCancel.Gtk.Container+ContainerChild
			global::Gtk.Alignment w37 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w38 = new global::Gtk.HBox ();
			w38.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w39 = new global::Gtk.Image ();
			w39.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-cancel", global::Gtk.IconSize.Menu);
			w38.Add (w39);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w41 = new global::Gtk.Label ();
			w41.LabelProp = global::Mono.Unix.Catalog.GetString ("Cancel");
			w41.UseUnderline = true;
			w38.Add (w41);
			w37.Add (w38);
			this.btnCancel.Add (w37);
			this.hboxUpdateCancel.Add (this.btnCancel);
			global::Gtk.Box.BoxChild w45 = ((global::Gtk.Box.BoxChild)(this.hboxUpdateCancel [this.btnCancel]));
			w45.Position = 2;
			w45.Expand = false;
			w45.Fill = false;
			// Container child hboxUpdateCancel.Gtk.Box+BoxChild
			this.btnUpdate = new global::Gtk.Button ();
			this.btnUpdate.CanFocus = true;
			this.btnUpdate.Name = "btnUpdate";
			this.btnUpdate.UseUnderline = true;
			// Container child btnUpdate.Gtk.Container+ContainerChild
			global::Gtk.Alignment w46 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w47 = new global::Gtk.HBox ();
			w47.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w48 = new global::Gtk.Image ();
			w48.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-apply", global::Gtk.IconSize.Menu);
			w47.Add (w48);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w50 = new global::Gtk.Label ();
			w50.LabelProp = global::Mono.Unix.Catalog.GetString ("Update");
			w50.UseUnderline = true;
			w47.Add (w50);
			w46.Add (w47);
			this.btnUpdate.Add (w46);
			this.hboxUpdateCancel.Add (this.btnUpdate);
			global::Gtk.Box.BoxChild w54 = ((global::Gtk.Box.BoxChild)(this.hboxUpdateCancel [this.btnUpdate]));
			w54.Position = 3;
			w54.Expand = false;
			w54.Fill = false;
			this.vboxUser.Add (this.hboxUpdateCancel);
			global::Gtk.Box.BoxChild w55 = ((global::Gtk.Box.BoxChild)(this.vboxUser [this.hboxUpdateCancel]));
			w55.Position = 4;
			w55.Expand = false;
			w55.Fill = false;
			this.Add (this.vboxUser);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 404;
			this.DefaultHeight = 488;
			this.Show ();
			this.drpUsers.Changed += new global::System.EventHandler (this.OnDrpUsersChanged);
			this.btnDelete.Clicked += new global::System.EventHandler (this.OnBtnDeleteClicked);
			this.btnClose.Clicked += new global::System.EventHandler (this.OnBtnCloseClicked);
			this.btnCancel.Clicked += new global::System.EventHandler (this.OnBtnCancelClicked);
			this.btnUpdate.Clicked += new global::System.EventHandler (this.OnBtnUpdateClicked);
		}
	}
}
