
// This file has been generated by the GUI designer. Do not modify.
namespace Momiji
{
	public partial class frmUserEdit
	{
		private global::Gtk.VBox vboxUser;
		
		private global::Gtk.Label lblChooseUser;
		
		private global::Gtk.ComboBox drpUsers;
		
		private global::Gtk.HBox hboxActions;
		
		private global::Gtk.Button btnDelete;
		
		private global::Gtk.Frame frmUserInfo;
		
		private global::Gtk.Alignment GtkAlignment2;
		
		private global::Gtk.VBox vboxUserInfo;
		
		private global::Gtk.Label lblUsername;
		
		private global::Gtk.Entry txtUsername;
		
		private global::Gtk.Label lblName;
		
		private global::Gtk.Entry txtName;
		
		private global::Gtk.Label lblRank;
		
		private global::Gtk.ComboBox drpRank;
		
		private global::Gtk.Table tblPass;
		
		private global::Gtk.Label lblPass;
		
		private global::Gtk.Label lblPassRepeat;
		
		private global::Gtk.Entry txtPass;
		
		private global::Gtk.Entry txtPassRepeat;
		
		private global::Gtk.Label UserInfo;
		
		private global::Gtk.HBox hboxUpdateCancel;
		
		private global::Gtk.Button btnClose;
		
		private global::Gtk.Alignment alignment2;
		
		private global::Gtk.Button btnCancel;
		
		private global::Gtk.Button btnUpdate;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget Momiji.frmUserEdit
			this.Name = "Momiji.frmUserEdit";
			this.Title = global::Mono.Unix.Catalog.GetString ("Edit User");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			this.Modal = true;
			this.BorderWidth = ((uint)(8));
			// Container child Momiji.frmUserEdit.Gtk.Container+ContainerChild
			this.vboxUser = new global::Gtk.VBox ();
			this.vboxUser.Name = "vboxUser";
			this.vboxUser.Spacing = 6;
			this.vboxUser.BorderWidth = ((uint)(16));
			// Container child vboxUser.Gtk.Box+BoxChild
			this.lblChooseUser = new global::Gtk.Label ();
			this.lblChooseUser.Name = "lblChooseUser";
			this.lblChooseUser.Xalign = 0F;
			this.lblChooseUser.LabelProp = global::Mono.Unix.Catalog.GetString ("Choose a user:");
			this.vboxUser.Add (this.lblChooseUser);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vboxUser [this.lblChooseUser]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			// Container child vboxUser.Gtk.Box+BoxChild
			this.drpUsers = global::Gtk.ComboBox.NewText ();
			this.drpUsers.Name = "drpUsers";
			this.vboxUser.Add (this.drpUsers);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vboxUser [this.drpUsers]));
			w2.Position = 1;
			w2.Expand = false;
			w2.Fill = false;
			// Container child vboxUser.Gtk.Box+BoxChild
			this.hboxActions = new global::Gtk.HBox ();
			this.hboxActions.Name = "hboxActions";
			this.hboxActions.Spacing = 6;
			// Container child hboxActions.Gtk.Box+BoxChild
			this.btnDelete = new global::Gtk.Button ();
			this.btnDelete.CanFocus = true;
			this.btnDelete.Name = "btnDelete";
			this.btnDelete.UseUnderline = true;
			this.btnDelete.Label = global::Mono.Unix.Catalog.GetString ("Delete");
			global::Gtk.Image w3 = new global::Gtk.Image ();
			w3.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-delete", global::Gtk.IconSize.Menu);
			this.btnDelete.Image = w3;
			this.hboxActions.Add (this.btnDelete);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hboxActions [this.btnDelete]));
			w4.Position = 0;
			w4.Expand = false;
			w4.Fill = false;
			this.vboxUser.Add (this.hboxActions);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vboxUser [this.hboxActions]));
			w5.Position = 2;
			w5.Expand = false;
			w5.Fill = false;
			// Container child vboxUser.Gtk.Box+BoxChild
			this.frmUserInfo = new global::Gtk.Frame ();
			this.frmUserInfo.Name = "frmUserInfo";
			this.frmUserInfo.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child frmUserInfo.Gtk.Container+ContainerChild
			this.GtkAlignment2 = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
			this.GtkAlignment2.Name = "GtkAlignment2";
			this.GtkAlignment2.LeftPadding = ((uint)(12));
			this.GtkAlignment2.BorderWidth = ((uint)(8));
			// Container child GtkAlignment2.Gtk.Container+ContainerChild
			this.vboxUserInfo = new global::Gtk.VBox ();
			this.vboxUserInfo.Name = "vboxUserInfo";
			this.vboxUserInfo.Spacing = 6;
			// Container child vboxUserInfo.Gtk.Box+BoxChild
			this.lblUsername = new global::Gtk.Label ();
			this.lblUsername.Name = "lblUsername";
			this.lblUsername.Xalign = 0F;
			this.lblUsername.LabelProp = global::Mono.Unix.Catalog.GetString ("Username:");
			this.vboxUserInfo.Add (this.lblUsername);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vboxUserInfo [this.lblUsername]));
			w6.Position = 0;
			w6.Expand = false;
			w6.Fill = false;
			// Container child vboxUserInfo.Gtk.Box+BoxChild
			this.txtUsername = new global::Gtk.Entry ();
			this.txtUsername.CanFocus = true;
			this.txtUsername.Name = "txtUsername";
			this.txtUsername.IsEditable = true;
			this.txtUsername.InvisibleChar = '●';
			this.vboxUserInfo.Add (this.txtUsername);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.vboxUserInfo [this.txtUsername]));
			w7.Position = 1;
			w7.Expand = false;
			w7.Fill = false;
			// Container child vboxUserInfo.Gtk.Box+BoxChild
			this.lblName = new global::Gtk.Label ();
			this.lblName.Name = "lblName";
			this.lblName.Xalign = 0F;
			this.lblName.LabelProp = global::Mono.Unix.Catalog.GetString ("First and Lastname:");
			this.vboxUserInfo.Add (this.lblName);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.vboxUserInfo [this.lblName]));
			w8.Position = 2;
			w8.Expand = false;
			w8.Fill = false;
			// Container child vboxUserInfo.Gtk.Box+BoxChild
			this.txtName = new global::Gtk.Entry ();
			this.txtName.CanFocus = true;
			this.txtName.Name = "txtName";
			this.txtName.IsEditable = true;
			this.txtName.InvisibleChar = '●';
			this.vboxUserInfo.Add (this.txtName);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.vboxUserInfo [this.txtName]));
			w9.Position = 3;
			w9.Expand = false;
			w9.Fill = false;
			// Container child vboxUserInfo.Gtk.Box+BoxChild
			this.lblRank = new global::Gtk.Label ();
			this.lblRank.Name = "lblRank";
			this.lblRank.Xalign = 0F;
			this.lblRank.LabelProp = global::Mono.Unix.Catalog.GetString ("Rank:");
			this.vboxUserInfo.Add (this.lblRank);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.vboxUserInfo [this.lblRank]));
			w10.Position = 4;
			w10.Expand = false;
			w10.Fill = false;
			// Container child vboxUserInfo.Gtk.Box+BoxChild
			this.drpRank = global::Gtk.ComboBox.NewText ();
			this.drpRank.AppendText (global::Mono.Unix.Catalog.GetString ("0 - Login"));
			this.drpRank.AppendText (global::Mono.Unix.Catalog.GetString ("1 - Gallery Store Sales"));
			this.drpRank.AppendText (global::Mono.Unix.Catalog.GetString ("2 - Quick Sales"));
			this.drpRank.AppendText (global::Mono.Unix.Catalog.GetString ("3 - Auction Sales"));
			this.drpRank.AppendText (global::Mono.Unix.Catalog.GetString ("4 - Re-Print Receipts"));
			this.drpRank.AppendText (global::Mono.Unix.Catalog.GetString ("5 - Check-in Artists"));
			this.drpRank.AppendText (global::Mono.Unix.Catalog.GetString ("6 - Bidding sheets, Check-out, Bidders"));
			this.drpRank.AppendText (global::Mono.Unix.Catalog.GetString ("7 - Manage artist stock"));
			this.drpRank.AppendText (global::Mono.Unix.Catalog.GetString ("8 - View Activity logs"));
			this.drpRank.AppendText (global::Mono.Unix.Catalog.GetString ("9 - View Monetary activity logs"));
			this.drpRank.AppendText (global::Mono.Unix.Catalog.GetString ("10 - Manage Treasury/refunds"));
			this.drpRank.AppendText (global::Mono.Unix.Catalog.GetString ("11 - Administrator"));
			this.drpRank.Name = "drpRank";
			this.vboxUserInfo.Add (this.drpRank);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.vboxUserInfo [this.drpRank]));
			w11.Position = 5;
			w11.Expand = false;
			w11.Fill = false;
			// Container child vboxUserInfo.Gtk.Box+BoxChild
			this.tblPass = new global::Gtk.Table (((uint)(2)), ((uint)(2)), false);
			this.tblPass.Name = "tblPass";
			this.tblPass.RowSpacing = ((uint)(6));
			this.tblPass.ColumnSpacing = ((uint)(6));
			// Container child tblPass.Gtk.Table+TableChild
			this.lblPass = new global::Gtk.Label ();
			this.lblPass.Name = "lblPass";
			this.lblPass.Xalign = 0F;
			this.lblPass.LabelProp = global::Mono.Unix.Catalog.GetString ("Password");
			this.tblPass.Add (this.lblPass);
			global::Gtk.Table.TableChild w12 = ((global::Gtk.Table.TableChild)(this.tblPass [this.lblPass]));
			w12.XOptions = ((global::Gtk.AttachOptions)(4));
			w12.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tblPass.Gtk.Table+TableChild
			this.lblPassRepeat = new global::Gtk.Label ();
			this.lblPassRepeat.Name = "lblPassRepeat";
			this.lblPassRepeat.Xalign = 0F;
			this.lblPassRepeat.LabelProp = global::Mono.Unix.Catalog.GetString ("Retype Password:");
			this.tblPass.Add (this.lblPassRepeat);
			global::Gtk.Table.TableChild w13 = ((global::Gtk.Table.TableChild)(this.tblPass [this.lblPassRepeat]));
			w13.LeftAttach = ((uint)(1));
			w13.RightAttach = ((uint)(2));
			w13.XOptions = ((global::Gtk.AttachOptions)(4));
			w13.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tblPass.Gtk.Table+TableChild
			this.txtPass = new global::Gtk.Entry ();
			this.txtPass.CanFocus = true;
			this.txtPass.Name = "txtPass";
			this.txtPass.IsEditable = true;
			this.txtPass.Visibility = false;
			this.txtPass.InvisibleChar = '●';
			this.tblPass.Add (this.txtPass);
			global::Gtk.Table.TableChild w14 = ((global::Gtk.Table.TableChild)(this.tblPass [this.txtPass]));
			w14.TopAttach = ((uint)(1));
			w14.BottomAttach = ((uint)(2));
			w14.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tblPass.Gtk.Table+TableChild
			this.txtPassRepeat = new global::Gtk.Entry ();
			this.txtPassRepeat.CanFocus = true;
			this.txtPassRepeat.Name = "txtPassRepeat";
			this.txtPassRepeat.IsEditable = true;
			this.txtPassRepeat.Visibility = false;
			this.txtPassRepeat.InvisibleChar = '●';
			this.tblPass.Add (this.txtPassRepeat);
			global::Gtk.Table.TableChild w15 = ((global::Gtk.Table.TableChild)(this.tblPass [this.txtPassRepeat]));
			w15.TopAttach = ((uint)(1));
			w15.BottomAttach = ((uint)(2));
			w15.LeftAttach = ((uint)(1));
			w15.RightAttach = ((uint)(2));
			w15.YOptions = ((global::Gtk.AttachOptions)(4));
			this.vboxUserInfo.Add (this.tblPass);
			global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.vboxUserInfo [this.tblPass]));
			w16.Position = 6;
			w16.Expand = false;
			w16.Fill = false;
			this.GtkAlignment2.Add (this.vboxUserInfo);
			this.frmUserInfo.Add (this.GtkAlignment2);
			this.UserInfo = new global::Gtk.Label ();
			this.UserInfo.Name = "UserInfo";
			this.UserInfo.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>User Info</b>");
			this.UserInfo.UseMarkup = true;
			this.frmUserInfo.LabelWidget = this.UserInfo;
			this.vboxUser.Add (this.frmUserInfo);
			global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.vboxUser [this.frmUserInfo]));
			w19.Position = 3;
			w19.Expand = false;
			w19.Fill = false;
			// Container child vboxUser.Gtk.Box+BoxChild
			this.hboxUpdateCancel = new global::Gtk.HBox ();
			this.hboxUpdateCancel.Name = "hboxUpdateCancel";
			this.hboxUpdateCancel.Spacing = 6;
			// Container child hboxUpdateCancel.Gtk.Box+BoxChild
			this.btnClose = new global::Gtk.Button ();
			this.btnClose.CanFocus = true;
			this.btnClose.Name = "btnClose";
			this.btnClose.UseUnderline = true;
			this.btnClose.Label = global::Mono.Unix.Catalog.GetString ("Close");
			global::Gtk.Image w20 = new global::Gtk.Image ();
			w20.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-close", global::Gtk.IconSize.Menu);
			this.btnClose.Image = w20;
			this.hboxUpdateCancel.Add (this.btnClose);
			global::Gtk.Box.BoxChild w21 = ((global::Gtk.Box.BoxChild)(this.hboxUpdateCancel [this.btnClose]));
			w21.Position = 0;
			w21.Expand = false;
			w21.Fill = false;
			// Container child hboxUpdateCancel.Gtk.Box+BoxChild
			this.alignment2 = new global::Gtk.Alignment (0.5F, 0.5F, 1F, 1F);
			this.alignment2.Name = "alignment2";
			this.hboxUpdateCancel.Add (this.alignment2);
			global::Gtk.Box.BoxChild w22 = ((global::Gtk.Box.BoxChild)(this.hboxUpdateCancel [this.alignment2]));
			w22.Position = 1;
			// Container child hboxUpdateCancel.Gtk.Box+BoxChild
			this.btnCancel = new global::Gtk.Button ();
			this.btnCancel.CanFocus = true;
			this.btnCancel.Name = "btnCancel";
			this.btnCancel.UseUnderline = true;
			this.btnCancel.Label = global::Mono.Unix.Catalog.GetString ("Cancel");
			global::Gtk.Image w23 = new global::Gtk.Image ();
			w23.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-cancel", global::Gtk.IconSize.Menu);
			this.btnCancel.Image = w23;
			this.hboxUpdateCancel.Add (this.btnCancel);
			global::Gtk.Box.BoxChild w24 = ((global::Gtk.Box.BoxChild)(this.hboxUpdateCancel [this.btnCancel]));
			w24.Position = 2;
			w24.Expand = false;
			w24.Fill = false;
			// Container child hboxUpdateCancel.Gtk.Box+BoxChild
			this.btnUpdate = new global::Gtk.Button ();
			this.btnUpdate.CanFocus = true;
			this.btnUpdate.Name = "btnUpdate";
			this.btnUpdate.UseUnderline = true;
			this.btnUpdate.Label = global::Mono.Unix.Catalog.GetString ("Update");
			global::Gtk.Image w25 = new global::Gtk.Image ();
			w25.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-apply", global::Gtk.IconSize.Menu);
			this.btnUpdate.Image = w25;
			this.hboxUpdateCancel.Add (this.btnUpdate);
			global::Gtk.Box.BoxChild w26 = ((global::Gtk.Box.BoxChild)(this.hboxUpdateCancel [this.btnUpdate]));
			w26.Position = 3;
			w26.Expand = false;
			w26.Fill = false;
			this.vboxUser.Add (this.hboxUpdateCancel);
			global::Gtk.Box.BoxChild w27 = ((global::Gtk.Box.BoxChild)(this.vboxUser [this.hboxUpdateCancel]));
			w27.Position = 4;
			w27.Expand = false;
			w27.Fill = false;
			this.Add (this.vboxUser);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 412;
			this.DefaultHeight = 488;
			this.Show ();
			this.drpUsers.Changed += new global::System.EventHandler (this.OnDrpUsersChanged);
			this.btnDelete.Clicked += new global::System.EventHandler (this.OnBtnDeleteClicked);
			this.btnClose.Clicked += new global::System.EventHandler (this.OnBtnCloseClicked);
			this.btnCancel.Clicked += new global::System.EventHandler (this.OnBtnCancelClicked);
			this.btnUpdate.Clicked += new global::System.EventHandler (this.OnBtnUpdateClicked);
		}
	}
}
