
// This file has been generated by the GUI designer. Do not modify.
namespace Momiji
{
	public partial class frmArtistCheckout
	{
		private global::Gtk.Table tableANCheckout;
		private global::Gtk.Frame frameArtistInfo;
		private global::Gtk.Alignment GtkAlignArtistInfo;
		private global::Gtk.VBox vboxArtistInfo;
		private global::Gtk.Table tableArtistInfo;
		private global::Gtk.Label lblANID;
		private global::Gtk.Label lblANName;
		private global::Gtk.Label lblArtistID;
		private global::Gtk.Label lblArtistName;
		private global::Gtk.HBox hboxArtistInfoButton;
		private global::Gtk.Button buttonCancel;
		private global::Gtk.Label GtkLabel6;
		private global::Gtk.Frame frameStep1;
		private global::Gtk.Alignment GtkAlignment5;
		private global::Gtk.VBox vboxStep1;
		private global::Gtk.Label lblGenSaleSum;
		private global::Gtk.Button btnGenSaleSum;
		private global::Gtk.Label lblStep1;
		private global::Gtk.Frame frameStep4;
		private global::Gtk.Alignment GtkSAlignStep4;
		private global::Gtk.VBox vbox4;
		private global::Gtk.CheckButton chkStep1;
		private global::Gtk.CheckButton chkStep2;
		private global::Gtk.CheckButton chkStep3;
		private global::Gtk.Button button6;
		private global::Gtk.Label lblStep4;
		private global::Gtk.HBox hboxStep23;
		private global::Gtk.Frame frameStep2;
		private global::Gtk.Alignment GtkAlignStep2;
		private global::Gtk.VBox vboxStep2;
		private global::Gtk.Label lblIMPORTANT;
		private global::Gtk.Label lblIMPORTANTDetails;
		private global::Gtk.Label lblStep2;
		private global::Gtk.Frame frameStep3;
		private global::Gtk.Alignment GtkAlignStep3;
		private global::Gtk.VBox vboxStep3;
		private global::Gtk.Label lblStep3a;
		private global::Gtk.Label lblStep3b;
		private global::Gtk.Label lblStep3;
		
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget Momiji.frmArtistCheckout
			this.Name = "Momiji.frmArtistCheckout";
			this.Title = global::Mono.Unix.Catalog.GetString ("Artist Checkout");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			this.BorderWidth = ((uint)(8));
			this.Resizable = false;
			// Container child Momiji.frmArtistCheckout.Gtk.Container+ContainerChild
			this.tableANCheckout = new global::Gtk.Table (((uint)(2)), ((uint)(2)), false);
			this.tableANCheckout.Name = "tableANCheckout";
			this.tableANCheckout.RowSpacing = ((uint)(6));
			this.tableANCheckout.ColumnSpacing = ((uint)(6));
			// Container child tableANCheckout.Gtk.Table+TableChild
			this.frameArtistInfo = new global::Gtk.Frame ();
			this.frameArtistInfo.Name = "frameArtistInfo";
			this.frameArtistInfo.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child frameArtistInfo.Gtk.Container+ContainerChild
			this.GtkAlignArtistInfo = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
			this.GtkAlignArtistInfo.Name = "GtkAlignArtistInfo";
			this.GtkAlignArtistInfo.LeftPadding = ((uint)(8));
			this.GtkAlignArtistInfo.TopPadding = ((uint)(8));
			this.GtkAlignArtistInfo.RightPadding = ((uint)(8));
			this.GtkAlignArtistInfo.BottomPadding = ((uint)(8));
			// Container child GtkAlignArtistInfo.Gtk.Container+ContainerChild
			this.vboxArtistInfo = new global::Gtk.VBox ();
			this.vboxArtistInfo.Name = "vboxArtistInfo";
			this.vboxArtistInfo.Spacing = 6;
			// Container child vboxArtistInfo.Gtk.Box+BoxChild
			this.tableArtistInfo = new global::Gtk.Table (((uint)(2)), ((uint)(2)), false);
			this.tableArtistInfo.Name = "tableArtistInfo";
			this.tableArtistInfo.RowSpacing = ((uint)(6));
			this.tableArtistInfo.ColumnSpacing = ((uint)(6));
			// Container child tableArtistInfo.Gtk.Table+TableChild
			this.lblANID = new global::Gtk.Label ();
			this.lblANID.Name = "lblANID";
			this.lblANID.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Artist ID # :</b>");
			this.lblANID.UseMarkup = true;
			this.tableArtistInfo.Add (this.lblANID);
			global::Gtk.Table.TableChild w1 = ((global::Gtk.Table.TableChild)(this.tableArtistInfo [this.lblANID]));
			w1.TopAttach = ((uint)(1));
			w1.BottomAttach = ((uint)(2));
			w1.XOptions = ((global::Gtk.AttachOptions)(4));
			w1.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tableArtistInfo.Gtk.Table+TableChild
			this.lblANName = new global::Gtk.Label ();
			this.lblANName.Name = "lblANName";
			this.lblANName.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Artist Name :</b>");
			this.lblANName.UseMarkup = true;
			this.tableArtistInfo.Add (this.lblANName);
			global::Gtk.Table.TableChild w2 = ((global::Gtk.Table.TableChild)(this.tableArtistInfo [this.lblANName]));
			w2.XOptions = ((global::Gtk.AttachOptions)(4));
			w2.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tableArtistInfo.Gtk.Table+TableChild
			this.lblArtistID = new global::Gtk.Label ();
			this.lblArtistID.Name = "lblArtistID";
			this.lblArtistID.LabelProp = global::Mono.Unix.Catalog.GetString ("N/A");
			this.tableArtistInfo.Add (this.lblArtistID);
			global::Gtk.Table.TableChild w3 = ((global::Gtk.Table.TableChild)(this.tableArtistInfo [this.lblArtistID]));
			w3.TopAttach = ((uint)(1));
			w3.BottomAttach = ((uint)(2));
			w3.LeftAttach = ((uint)(1));
			w3.RightAttach = ((uint)(2));
			w3.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tableArtistInfo.Gtk.Table+TableChild
			this.lblArtistName = new global::Gtk.Label ();
			this.lblArtistName.Name = "lblArtistName";
			this.lblArtistName.LabelProp = global::Mono.Unix.Catalog.GetString ("N/A");
			this.tableArtistInfo.Add (this.lblArtistName);
			global::Gtk.Table.TableChild w4 = ((global::Gtk.Table.TableChild)(this.tableArtistInfo [this.lblArtistName]));
			w4.LeftAttach = ((uint)(1));
			w4.RightAttach = ((uint)(2));
			w4.YOptions = ((global::Gtk.AttachOptions)(4));
			this.vboxArtistInfo.Add (this.tableArtistInfo);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vboxArtistInfo [this.tableArtistInfo]));
			w5.Position = 0;
			w5.Expand = false;
			w5.Fill = false;
			w5.Padding = ((uint)(8));
			// Container child vboxArtistInfo.Gtk.Box+BoxChild
			this.hboxArtistInfoButton = new global::Gtk.HBox ();
			this.hboxArtistInfoButton.Name = "hboxArtistInfoButton";
			this.hboxArtistInfoButton.Spacing = 6;
			// Container child hboxArtistInfoButton.Gtk.Box+BoxChild
			this.buttonCancel = new global::Gtk.Button ();
			this.buttonCancel.CanFocus = true;
			this.buttonCancel.Name = "buttonCancel";
			this.buttonCancel.UseUnderline = true;
			// Container child buttonCancel.Gtk.Container+ContainerChild
			global::Gtk.Alignment w6 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w7 = new global::Gtk.HBox ();
			w7.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w8 = new global::Gtk.Image ();
			w8.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-cancel", global::Gtk.IconSize.Menu);
			w7.Add (w8);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w10 = new global::Gtk.Label ();
			w10.LabelProp = global::Mono.Unix.Catalog.GetString ("Cancel");
			w10.UseUnderline = true;
			w7.Add (w10);
			w6.Add (w7);
			this.buttonCancel.Add (w6);
			this.hboxArtistInfoButton.Add (this.buttonCancel);
			global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.hboxArtistInfoButton [this.buttonCancel]));
			w14.Position = 1;
			w14.Expand = false;
			w14.Fill = false;
			this.vboxArtistInfo.Add (this.hboxArtistInfoButton);
			global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.vboxArtistInfo [this.hboxArtistInfoButton]));
			w15.Position = 1;
			w15.Expand = false;
			w15.Fill = false;
			this.GtkAlignArtistInfo.Add (this.vboxArtistInfo);
			this.frameArtistInfo.Add (this.GtkAlignArtistInfo);
			this.GtkLabel6 = new global::Gtk.Label ();
			this.GtkLabel6.Name = "GtkLabel6";
			this.GtkLabel6.LabelProp = global::Mono.Unix.Catalog.GetString ("Artist Information");
			this.GtkLabel6.UseMarkup = true;
			this.frameArtistInfo.LabelWidget = this.GtkLabel6;
			this.tableANCheckout.Add (this.frameArtistInfo);
			global::Gtk.Table.TableChild w18 = ((global::Gtk.Table.TableChild)(this.tableANCheckout [this.frameArtistInfo]));
			w18.TopAttach = ((uint)(1));
			w18.BottomAttach = ((uint)(2));
			w18.LeftAttach = ((uint)(1));
			w18.RightAttach = ((uint)(2));
			w18.XOptions = ((global::Gtk.AttachOptions)(4));
			w18.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tableANCheckout.Gtk.Table+TableChild
			this.frameStep1 = new global::Gtk.Frame ();
			this.frameStep1.Name = "frameStep1";
			this.frameStep1.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child frameStep1.Gtk.Container+ContainerChild
			this.GtkAlignment5 = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
			this.GtkAlignment5.Name = "GtkAlignment5";
			this.GtkAlignment5.LeftPadding = ((uint)(8));
			this.GtkAlignment5.RightPadding = ((uint)(8));
			// Container child GtkAlignment5.Gtk.Container+ContainerChild
			this.vboxStep1 = new global::Gtk.VBox ();
			this.vboxStep1.Name = "vboxStep1";
			this.vboxStep1.Spacing = 6;
			// Container child vboxStep1.Gtk.Box+BoxChild
			this.lblGenSaleSum = new global::Gtk.Label ();
			this.lblGenSaleSum.Name = "lblGenSaleSum";
			this.lblGenSaleSum.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>First, let's show the artist their earnings. \nClick the button below for a page \ndisplaying the artists' sales summary \n(make sure you print it!)</b>");
			this.lblGenSaleSum.UseMarkup = true;
			this.vboxStep1.Add (this.lblGenSaleSum);
			global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.vboxStep1 [this.lblGenSaleSum]));
			w19.Position = 0;
			w19.Expand = false;
			w19.Fill = false;
			w19.Padding = ((uint)(8));
			// Container child vboxStep1.Gtk.Box+BoxChild
			this.btnGenSaleSum = new global::Gtk.Button ();
			this.btnGenSaleSum.CanFocus = true;
			this.btnGenSaleSum.Name = "btnGenSaleSum";
			this.btnGenSaleSum.UseUnderline = true;
			// Container child btnGenSaleSum.Gtk.Container+ContainerChild
			global::Gtk.Alignment w20 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w21 = new global::Gtk.HBox ();
			w21.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w22 = new global::Gtk.Image ();
			w22.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-new", global::Gtk.IconSize.Menu);
			w21.Add (w22);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w24 = new global::Gtk.Label ();
			w24.LabelProp = global::Mono.Unix.Catalog.GetString ("Generate Sales Summary");
			w24.UseUnderline = true;
			w21.Add (w24);
			w20.Add (w21);
			this.btnGenSaleSum.Add (w20);
			this.vboxStep1.Add (this.btnGenSaleSum);
			global::Gtk.Box.BoxChild w28 = ((global::Gtk.Box.BoxChild)(this.vboxStep1 [this.btnGenSaleSum]));
			w28.Position = 1;
			w28.Expand = false;
			w28.Fill = false;
			this.GtkAlignment5.Add (this.vboxStep1);
			this.frameStep1.Add (this.GtkAlignment5);
			this.lblStep1 = new global::Gtk.Label ();
			this.lblStep1.Name = "lblStep1";
			this.lblStep1.LabelProp = global::Mono.Unix.Catalog.GetString ("Step 1 :");
			this.frameStep1.LabelWidget = this.lblStep1;
			this.tableANCheckout.Add (this.frameStep1);
			global::Gtk.Table.TableChild w31 = ((global::Gtk.Table.TableChild)(this.tableANCheckout [this.frameStep1]));
			w31.XOptions = ((global::Gtk.AttachOptions)(4));
			w31.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tableANCheckout.Gtk.Table+TableChild
			this.frameStep4 = new global::Gtk.Frame ();
			this.frameStep4.Name = "frameStep4";
			this.frameStep4.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child frameStep4.Gtk.Container+ContainerChild
			this.GtkSAlignStep4 = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
			this.GtkSAlignStep4.Name = "GtkSAlignStep4";
			this.GtkSAlignStep4.LeftPadding = ((uint)(8));
			this.GtkSAlignStep4.TopPadding = ((uint)(8));
			this.GtkSAlignStep4.RightPadding = ((uint)(8));
			this.GtkSAlignStep4.BottomPadding = ((uint)(8));
			// Container child GtkSAlignStep4.Gtk.Container+ContainerChild
			this.vbox4 = new global::Gtk.VBox ();
			this.vbox4.Name = "vbox4";
			this.vbox4.Spacing = 6;
			// Container child vbox4.Gtk.Box+BoxChild
			this.chkStep1 = new global::Gtk.CheckButton ();
			this.chkStep1.CanFocus = true;
			this.chkStep1.Name = "chkStep1";
			this.chkStep1.Label = global::Mono.Unix.Catalog.GetString ("Step 1 Complete");
			this.chkStep1.DrawIndicator = true;
			this.chkStep1.UseUnderline = true;
			this.vbox4.Add (this.chkStep1);
			global::Gtk.Box.BoxChild w32 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.chkStep1]));
			w32.Position = 0;
			w32.Expand = false;
			w32.Fill = false;
			// Container child vbox4.Gtk.Box+BoxChild
			this.chkStep2 = new global::Gtk.CheckButton ();
			this.chkStep2.CanFocus = true;
			this.chkStep2.Name = "chkStep2";
			this.chkStep2.Label = global::Mono.Unix.Catalog.GetString ("Step 2 Complete");
			this.chkStep2.DrawIndicator = true;
			this.chkStep2.UseUnderline = true;
			this.vbox4.Add (this.chkStep2);
			global::Gtk.Box.BoxChild w33 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.chkStep2]));
			w33.Position = 1;
			w33.Expand = false;
			w33.Fill = false;
			// Container child vbox4.Gtk.Box+BoxChild
			this.chkStep3 = new global::Gtk.CheckButton ();
			this.chkStep3.CanFocus = true;
			this.chkStep3.Name = "chkStep3";
			this.chkStep3.Label = global::Mono.Unix.Catalog.GetString ("Step 3 Complete");
			this.chkStep3.DrawIndicator = true;
			this.chkStep3.UseUnderline = true;
			this.vbox4.Add (this.chkStep3);
			global::Gtk.Box.BoxChild w34 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.chkStep3]));
			w34.Position = 2;
			w34.Expand = false;
			w34.Fill = false;
			// Container child vbox4.Gtk.Box+BoxChild
			this.button6 = new global::Gtk.Button ();
			this.button6.CanFocus = true;
			this.button6.Name = "button6";
			this.button6.UseUnderline = true;
			// Container child button6.Gtk.Container+ContainerChild
			global::Gtk.Alignment w35 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w36 = new global::Gtk.HBox ();
			w36.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w37 = new global::Gtk.Image ();
			w37.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-ok", global::Gtk.IconSize.Menu);
			w36.Add (w37);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w39 = new global::Gtk.Label ();
			w39.LabelProp = global::Mono.Unix.Catalog.GetString ("Mark Artist as Checked out");
			w39.UseUnderline = true;
			w36.Add (w39);
			w35.Add (w36);
			this.button6.Add (w35);
			this.vbox4.Add (this.button6);
			global::Gtk.Box.BoxChild w43 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.button6]));
			w43.Position = 3;
			w43.Expand = false;
			w43.Fill = false;
			this.GtkSAlignStep4.Add (this.vbox4);
			this.frameStep4.Add (this.GtkSAlignStep4);
			this.lblStep4 = new global::Gtk.Label ();
			this.lblStep4.Name = "lblStep4";
			this.lblStep4.LabelProp = global::Mono.Unix.Catalog.GetString ("Step 4 :");
			this.frameStep4.LabelWidget = this.lblStep4;
			this.tableANCheckout.Add (this.frameStep4);
			global::Gtk.Table.TableChild w46 = ((global::Gtk.Table.TableChild)(this.tableANCheckout [this.frameStep4]));
			w46.TopAttach = ((uint)(1));
			w46.BottomAttach = ((uint)(2));
			w46.XOptions = ((global::Gtk.AttachOptions)(4));
			w46.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tableANCheckout.Gtk.Table+TableChild
			this.hboxStep23 = new global::Gtk.HBox ();
			this.hboxStep23.Name = "hboxStep23";
			this.hboxStep23.Spacing = 6;
			// Container child hboxStep23.Gtk.Box+BoxChild
			this.frameStep2 = new global::Gtk.Frame ();
			this.frameStep2.Name = "frameStep2";
			this.frameStep2.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child frameStep2.Gtk.Container+ContainerChild
			this.GtkAlignStep2 = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
			this.GtkAlignStep2.Name = "GtkAlignStep2";
			this.GtkAlignStep2.LeftPadding = ((uint)(8));
			this.GtkAlignStep2.TopPadding = ((uint)(8));
			this.GtkAlignStep2.RightPadding = ((uint)(8));
			this.GtkAlignStep2.BottomPadding = ((uint)(8));
			this.GtkAlignStep2.BorderWidth = ((uint)(8));
			// Container child GtkAlignStep2.Gtk.Container+ContainerChild
			this.vboxStep2 = new global::Gtk.VBox ();
			this.vboxStep2.Name = "vboxStep2";
			this.vboxStep2.Spacing = 6;
			// Container child vboxStep2.Gtk.Box+BoxChild
			this.lblIMPORTANT = new global::Gtk.Label ();
			this.lblIMPORTANT.Name = "lblIMPORTANT";
			this.lblIMPORTANT.LabelProp = global::Mono.Unix.Catalog.GetString ("<span foreground=\"red\" size=\"x-large\"><b>IMPORTANT</b></span>");
			this.lblIMPORTANT.UseMarkup = true;
			this.vboxStep2.Add (this.lblIMPORTANT);
			global::Gtk.Box.BoxChild w47 = ((global::Gtk.Box.BoxChild)(this.vboxStep2 [this.lblIMPORTANT]));
			w47.Position = 0;
			w47.Expand = false;
			w47.Fill = false;
			// Container child vboxStep2.Gtk.Box+BoxChild
			this.lblIMPORTANTDetails = new global::Gtk.Label ();
			this.lblIMPORTANTDetails.Name = "lblIMPORTANTDetails";
			this.lblIMPORTANTDetails.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Once you go over the artists' sales\nsummary, make sure the artist has \ncollected all of his/her art work, \nwhere applicable.</b>");
			this.lblIMPORTANTDetails.UseMarkup = true;
			this.vboxStep2.Add (this.lblIMPORTANTDetails);
			global::Gtk.Box.BoxChild w48 = ((global::Gtk.Box.BoxChild)(this.vboxStep2 [this.lblIMPORTANTDetails]));
			w48.Position = 1;
			w48.Expand = false;
			w48.Fill = false;
			this.GtkAlignStep2.Add (this.vboxStep2);
			this.frameStep2.Add (this.GtkAlignStep2);
			this.lblStep2 = new global::Gtk.Label ();
			this.lblStep2.Name = "lblStep2";
			this.lblStep2.LabelProp = global::Mono.Unix.Catalog.GetString ("Step 2 :");
			this.lblStep2.UseMarkup = true;
			this.frameStep2.LabelWidget = this.lblStep2;
			this.hboxStep23.Add (this.frameStep2);
			global::Gtk.Box.BoxChild w51 = ((global::Gtk.Box.BoxChild)(this.hboxStep23 [this.frameStep2]));
			w51.Position = 0;
			w51.Expand = false;
			w51.Fill = false;
			// Container child hboxStep23.Gtk.Box+BoxChild
			this.frameStep3 = new global::Gtk.Frame ();
			this.frameStep3.Name = "frameStep3";
			this.frameStep3.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child frameStep3.Gtk.Container+ContainerChild
			this.GtkAlignStep3 = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
			this.GtkAlignStep3.Name = "GtkAlignStep3";
			this.GtkAlignStep3.LeftPadding = ((uint)(8));
			this.GtkAlignStep3.TopPadding = ((uint)(8));
			this.GtkAlignStep3.RightPadding = ((uint)(8));
			this.GtkAlignStep3.BottomPadding = ((uint)(8));
			// Container child GtkAlignStep3.Gtk.Container+ContainerChild
			this.vboxStep3 = new global::Gtk.VBox ();
			this.vboxStep3.Name = "vboxStep3";
			this.vboxStep3.Spacing = 6;
			// Container child vboxStep3.Gtk.Box+BoxChild
			this.lblStep3a = new global::Gtk.Label ();
			this.lblStep3a.Name = "lblStep3a";
			this.lblStep3a.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Make sure to pay the artist in\nan envelope, as well as including\ntheir copy of the sales summary.</b>");
			this.lblStep3a.UseMarkup = true;
			this.vboxStep3.Add (this.lblStep3a);
			global::Gtk.Box.BoxChild w52 = ((global::Gtk.Box.BoxChild)(this.vboxStep3 [this.lblStep3a]));
			w52.Position = 0;
			w52.Expand = false;
			w52.Fill = false;
			// Container child vboxStep3.Gtk.Box+BoxChild
			this.lblStep3b = new global::Gtk.Label ();
			this.lblStep3b.Name = "lblStep3b";
			this.lblStep3b.LabelProp = global::Mono.Unix.Catalog.GetString ("If their earnings are $500 or more,\noffer a cheque, and ask for help.");
			this.vboxStep3.Add (this.lblStep3b);
			global::Gtk.Box.BoxChild w53 = ((global::Gtk.Box.BoxChild)(this.vboxStep3 [this.lblStep3b]));
			w53.Position = 1;
			w53.Expand = false;
			w53.Fill = false;
			this.GtkAlignStep3.Add (this.vboxStep3);
			this.frameStep3.Add (this.GtkAlignStep3);
			this.lblStep3 = new global::Gtk.Label ();
			this.lblStep3.Name = "lblStep3";
			this.lblStep3.LabelProp = global::Mono.Unix.Catalog.GetString ("Step 3 :");
			this.frameStep3.LabelWidget = this.lblStep3;
			this.hboxStep23.Add (this.frameStep3);
			global::Gtk.Box.BoxChild w56 = ((global::Gtk.Box.BoxChild)(this.hboxStep23 [this.frameStep3]));
			w56.Position = 1;
			w56.Expand = false;
			w56.Fill = false;
			this.tableANCheckout.Add (this.hboxStep23);
			global::Gtk.Table.TableChild w57 = ((global::Gtk.Table.TableChild)(this.tableANCheckout [this.hboxStep23]));
			w57.LeftAttach = ((uint)(1));
			w57.RightAttach = ((uint)(2));
			w57.XOptions = ((global::Gtk.AttachOptions)(4));
			w57.YOptions = ((global::Gtk.AttachOptions)(4));
			this.Add (this.tableANCheckout);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 829;
			this.DefaultHeight = 360;
			this.Show ();
		}
	}
}
