
// This file has been generated by the GUI designer. Do not modify.
namespace Momiji
{
	public partial class frmMenu
	{
		private global::Gtk.VBox vbox2;
		
		private global::Gtk.HBox hbox8;
		
		private global::Gtk.Fixed fixedQuickSale;
		
		private global::Gtk.Button btnQuickSale;
		
		private global::Gtk.Image imgQuickSale;
		
		private global::Gtk.Fixed fixedAuctionSale;
		
		private global::Gtk.Button btnAuctionSale;
		
		private global::Gtk.Image imgAuctionSale;
		
		private global::Gtk.Fixed fixedGalleryStoreSale;
		
		private global::Gtk.Button btnGalleryStoreSale;
		
		private global::Gtk.Image imgGalleryStoreSale;
		
		private global::Gtk.HBox hbox9;
		
		private global::Gtk.Button btnLogout;
		
		private global::Gtk.Label lblGreeting;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget Momiji.frmMenu
			this.Name = "Momiji.frmMenu";
			this.Title = global::Mono.Unix.Catalog.GetString ("frmMenu");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child Momiji.frmMenu.Gtk.Container+ContainerChild
			this.vbox2 = new global::Gtk.VBox ();
			this.vbox2.Name = "vbox2";
			this.vbox2.Spacing = 8;
			// Container child vbox2.Gtk.Box+BoxChild
			this.hbox8 = new global::Gtk.HBox ();
			this.hbox8.Name = "hbox8";
			this.hbox8.Spacing = 8;
			this.hbox8.BorderWidth = ((uint)(16));
			// Container child hbox8.Gtk.Box+BoxChild
			this.fixedQuickSale = new global::Gtk.Fixed ();
			this.fixedQuickSale.Name = "fixedQuickSale";
			this.fixedQuickSale.HasWindow = false;
			// Container child fixedQuickSale.Gtk.Fixed+FixedChild
			this.btnQuickSale = new global::Gtk.Button ();
			this.btnQuickSale.WidthRequest = 130;
			this.btnQuickSale.HeightRequest = 130;
			this.btnQuickSale.CanFocus = true;
			this.btnQuickSale.Name = "btnQuickSale";
			this.btnQuickSale.UseUnderline = true;
			this.btnQuickSale.Yalign = 1F;
			this.btnQuickSale.Label = global::Mono.Unix.Catalog.GetString ("Quick Sale");
			this.fixedQuickSale.Add (this.btnQuickSale);
			// Container child fixedQuickSale.Gtk.Fixed+FixedChild
			this.imgQuickSale = new global::Gtk.Image ();
			this.imgQuickSale.Name = "imgQuickSale";
			this.imgQuickSale.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("Momiji.Resources.tag-sale-icon.png");
			this.fixedQuickSale.Add (this.imgQuickSale);
			global::Gtk.Fixed.FixedChild w2 = ((global::Gtk.Fixed.FixedChild)(this.fixedQuickSale [this.imgQuickSale]));
			w2.X = 33;
			w2.Y = 24;
			this.hbox8.Add (this.fixedQuickSale);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox8 [this.fixedQuickSale]));
			w3.Position = 0;
			w3.Expand = false;
			w3.Fill = false;
			// Container child hbox8.Gtk.Box+BoxChild
			this.fixedAuctionSale = new global::Gtk.Fixed ();
			this.fixedAuctionSale.Name = "fixedAuctionSale";
			this.fixedAuctionSale.HasWindow = false;
			// Container child fixedAuctionSale.Gtk.Fixed+FixedChild
			this.btnAuctionSale = new global::Gtk.Button ();
			this.btnAuctionSale.WidthRequest = 130;
			this.btnAuctionSale.HeightRequest = 130;
			this.btnAuctionSale.CanFocus = true;
			this.btnAuctionSale.Name = "btnAuctionSale";
			this.btnAuctionSale.UseUnderline = true;
			this.btnAuctionSale.Yalign = 1F;
			this.btnAuctionSale.Label = global::Mono.Unix.Catalog.GetString ("AuctionSale");
			this.fixedAuctionSale.Add (this.btnAuctionSale);
			// Container child fixedAuctionSale.Gtk.Fixed+FixedChild
			this.imgAuctionSale = new global::Gtk.Image ();
			this.imgAuctionSale.Name = "imgAuctionSale";
			this.imgAuctionSale.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("Momiji.Resources.shopping-bag-icon.png");
			this.fixedAuctionSale.Add (this.imgAuctionSale);
			global::Gtk.Fixed.FixedChild w5 = ((global::Gtk.Fixed.FixedChild)(this.fixedAuctionSale [this.imgAuctionSale]));
			w5.X = 33;
			w5.Y = 24;
			this.hbox8.Add (this.fixedAuctionSale);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox8 [this.fixedAuctionSale]));
			w6.Position = 1;
			w6.Expand = false;
			w6.Fill = false;
			// Container child hbox8.Gtk.Box+BoxChild
			this.fixedGalleryStoreSale = new global::Gtk.Fixed ();
			this.fixedGalleryStoreSale.Name = "fixedGalleryStoreSale";
			this.fixedGalleryStoreSale.HasWindow = false;
			// Container child fixedGalleryStoreSale.Gtk.Fixed+FixedChild
			this.btnGalleryStoreSale = new global::Gtk.Button ();
			this.btnGalleryStoreSale.WidthRequest = 130;
			this.btnGalleryStoreSale.HeightRequest = 130;
			this.btnGalleryStoreSale.CanFocus = true;
			this.btnGalleryStoreSale.Name = "btnGalleryStoreSale";
			this.btnGalleryStoreSale.UseUnderline = true;
			this.btnGalleryStoreSale.Yalign = 1F;
			this.btnGalleryStoreSale.Label = global::Mono.Unix.Catalog.GetString ("Gallery Store Sale");
			this.fixedGalleryStoreSale.Add (this.btnGalleryStoreSale);
			// Container child fixedGalleryStoreSale.Gtk.Fixed+FixedChild
			this.imgGalleryStoreSale = new global::Gtk.Image ();
			this.imgGalleryStoreSale.Name = "imgGalleryStoreSale";
			this.imgGalleryStoreSale.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("Momiji.Resources.shopping-basket-icon.png");
			this.fixedGalleryStoreSale.Add (this.imgGalleryStoreSale);
			global::Gtk.Fixed.FixedChild w8 = ((global::Gtk.Fixed.FixedChild)(this.fixedGalleryStoreSale [this.imgGalleryStoreSale]));
			w8.X = 33;
			w8.Y = 24;
			this.hbox8.Add (this.fixedGalleryStoreSale);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.hbox8 [this.fixedGalleryStoreSale]));
			w9.Position = 2;
			w9.Expand = false;
			w9.Fill = false;
			this.vbox2.Add (this.hbox8);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.hbox8]));
			w10.Position = 1;
			w10.Expand = false;
			w10.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.hbox9 = new global::Gtk.HBox ();
			this.hbox9.Name = "hbox9";
			this.hbox9.Spacing = 8;
			this.hbox9.BorderWidth = ((uint)(16));
			// Container child hbox9.Gtk.Box+BoxChild
			this.btnLogout = new global::Gtk.Button ();
			this.btnLogout.WidthRequest = 394;
			this.btnLogout.CanFocus = true;
			this.btnLogout.Name = "btnLogout";
			this.btnLogout.UseUnderline = true;
			this.btnLogout.Label = global::Mono.Unix.Catalog.GetString ("Logout");
			this.hbox9.Add (this.btnLogout);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.hbox9 [this.btnLogout]));
			w11.Position = 0;
			this.vbox2.Add (this.hbox9);
			global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.hbox9]));
			w12.Position = 2;
			w12.Expand = false;
			w12.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.lblGreeting = new global::Gtk.Label ();
			this.lblGreeting.Name = "lblGreeting";
			this.lblGreeting.Xpad = 8;
			this.lblGreeting.Xalign = 0F;
			this.lblGreeting.LabelProp = global::Mono.Unix.Catalog.GetString ("lblGreeting");
			this.vbox2.Add (this.lblGreeting);
			global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.lblGreeting]));
			w13.Position = 3;
			w13.Expand = false;
			w13.Fill = false;
			w13.Padding = ((uint)(8));
			this.Add (this.vbox2);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 438;
			this.DefaultHeight = 300;
			this.Show ();
			this.btnQuickSale.Clicked += new global::System.EventHandler (this.OnBtnQuickSaleClicked);
			this.btnAuctionSale.Clicked += new global::System.EventHandler (this.OnBtnAuctionSaleClicked);
			this.btnGalleryStoreSale.Clicked += new global::System.EventHandler (this.OnBtnGalleryStoreSaleClicked);
			this.btnLogout.Clicked += new global::System.EventHandler (this.OnBtnLogoutClicked);
		}
	}
}
