
// This file has been generated by the GUI designer. Do not modify.
namespace Momiji
{
	public partial class frmCheckin
	{
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget Momiji.frmCheckin
			this.Name = "Momiji.frmCheckin";
			this.Title = global::Mono.Unix.Catalog.GetString ("frmCheckin");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 400;
			this.DefaultHeight = 300;
			this.Show ();
		}
	}
}
