
// This file has been generated by the GUI designer. Do not modify.
namespace Momiji
{
	public partial class frmLog
	{
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget Momiji.frmLog
			this.Name = "Momiji.frmLog";
			this.Title = global::Mono.Unix.Catalog.GetString ("frmLog");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 400;
			this.DefaultHeight = 300;
			this.Show ();
		}
	}
}
