
// This file has been generated by the GUI designer. Do not modify.
namespace Momiji
{
	public partial class frmMerchEditor
	{
		private global::Gtk.HBox hbox2;
		private global::Gtk.ScrolledWindow GtkScrolledWindow;
		private global::Gtk.NodeView lstMerch;
		private global::Gtk.VBox vbox3;
		private global::Gtk.Table table1;
		private global::Gtk.Label lblArtistID;
		private global::Gtk.Label lblArtistName;
		private global::Gtk.Label lblLabelArtistID;
		private global::Gtk.Label lblLabelArtistName;
		private global::Gtk.Frame frame1;
		private global::Gtk.Alignment GtkAlignment;
		private global::Gtk.VBox vbox4;
		private global::Gtk.HBox hbox3;
		private global::Gtk.Label lblPieceID;
		private global::Gtk.Entry txtPieceID;
		private global::Gtk.Button btnGenID;
		private global::Gtk.HBox hbox4;
		private global::Gtk.Label lblPieceTitle;
		private global::Gtk.Entry txtPieceTitle;
		private global::Gtk.HBox hbox5;
		private global::Gtk.Label lblPieceMinimumBid;
		private global::Gtk.Entry txtPieceMinimumBid;
		private global::Gtk.CheckButton chkAAMB;
		private global::Gtk.HBox hbox6;
		private global::Gtk.Label lblQuickSale;
		private global::Gtk.Entry txtQuickSale;
		private global::Gtk.HBox hbox7;
		private global::Gtk.Label lblMedium;
		private global::Gtk.Entry txtMedium;
		private global::Gtk.Table table2;
		private global::Gtk.Button btnAdd;
		private global::Gtk.Button btnClear;
		private global::Gtk.Button btnDelete;
		private global::Gtk.Button btnUpdate;
		private global::Gtk.Button btnCreateSheet;
		private global::Gtk.Label lblPieceInfo;
		private global::Gtk.Button btnGenCS;
		private global::Gtk.Button btnCancel;
		
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget Momiji.frmMerchEditor
			this.Name = "Momiji.frmMerchEditor";
			this.Title = global::Mono.Unix.Catalog.GetString ("frmMerchEditor");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child Momiji.frmMerchEditor.Gtk.Container+ContainerChild
			this.hbox2 = new global::Gtk.HBox ();
			this.hbox2.Name = "hbox2";
			this.hbox2.Spacing = 6;
			this.hbox2.BorderWidth = ((uint)(8));
			// Container child hbox2.Gtk.Box+BoxChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.lstMerch = new global::Gtk.NodeView ();
			this.lstMerch.CanFocus = true;
			this.lstMerch.Name = "lstMerch";
			this.lstMerch.EnableSearch = false;
			this.GtkScrolledWindow.Add (this.lstMerch);
			this.hbox2.Add (this.GtkScrolledWindow);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.GtkScrolledWindow]));
			w2.Position = 0;
			// Container child hbox2.Gtk.Box+BoxChild
			this.vbox3 = new global::Gtk.VBox ();
			this.vbox3.Name = "vbox3";
			this.vbox3.Spacing = 6;
			// Container child vbox3.Gtk.Box+BoxChild
			this.table1 = new global::Gtk.Table (((uint)(2)), ((uint)(2)), false);
			this.table1.Name = "table1";
			this.table1.RowSpacing = ((uint)(6));
			this.table1.ColumnSpacing = ((uint)(6));
			// Container child table1.Gtk.Table+TableChild
			this.lblArtistID = new global::Gtk.Label ();
			this.lblArtistID.Name = "lblArtistID";
			this.lblArtistID.LabelProp = global::Mono.Unix.Catalog.GetString ("lblArtistID");
			this.table1.Add (this.lblArtistID);
			global::Gtk.Table.TableChild w3 = ((global::Gtk.Table.TableChild)(this.table1 [this.lblArtistID]));
			w3.LeftAttach = ((uint)(1));
			w3.RightAttach = ((uint)(2));
			w3.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.lblArtistName = new global::Gtk.Label ();
			this.lblArtistName.Name = "lblArtistName";
			this.lblArtistName.LabelProp = global::Mono.Unix.Catalog.GetString ("lblArtistName");
			this.table1.Add (this.lblArtistName);
			global::Gtk.Table.TableChild w4 = ((global::Gtk.Table.TableChild)(this.table1 [this.lblArtistName]));
			w4.TopAttach = ((uint)(1));
			w4.BottomAttach = ((uint)(2));
			w4.LeftAttach = ((uint)(1));
			w4.RightAttach = ((uint)(2));
			w4.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.lblLabelArtistID = new global::Gtk.Label ();
			this.lblLabelArtistID.Name = "lblLabelArtistID";
			this.lblLabelArtistID.Xalign = 1F;
			this.lblLabelArtistID.LabelProp = global::Mono.Unix.Catalog.GetString ("Artist ID :");
			this.table1.Add (this.lblLabelArtistID);
			global::Gtk.Table.TableChild w5 = ((global::Gtk.Table.TableChild)(this.table1 [this.lblLabelArtistID]));
			w5.XOptions = ((global::Gtk.AttachOptions)(4));
			w5.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.lblLabelArtistName = new global::Gtk.Label ();
			this.lblLabelArtistName.Name = "lblLabelArtistName";
			this.lblLabelArtistName.Xalign = 1F;
			this.lblLabelArtistName.LabelProp = global::Mono.Unix.Catalog.GetString ("Artist Name :");
			this.table1.Add (this.lblLabelArtistName);
			global::Gtk.Table.TableChild w6 = ((global::Gtk.Table.TableChild)(this.table1 [this.lblLabelArtistName]));
			w6.TopAttach = ((uint)(1));
			w6.BottomAttach = ((uint)(2));
			w6.XOptions = ((global::Gtk.AttachOptions)(4));
			w6.YOptions = ((global::Gtk.AttachOptions)(4));
			this.vbox3.Add (this.table1);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.table1]));
			w7.Position = 0;
			w7.Expand = false;
			w7.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.frame1 = new global::Gtk.Frame ();
			this.frame1.Name = "frame1";
			this.frame1.ShadowType = ((global::Gtk.ShadowType)(1));
			this.frame1.BorderWidth = ((uint)(8));
			// Container child frame1.Gtk.Container+ContainerChild
			this.GtkAlignment = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
			this.GtkAlignment.Name = "GtkAlignment";
			this.GtkAlignment.LeftPadding = ((uint)(12));
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			this.vbox4 = new global::Gtk.VBox ();
			this.vbox4.Name = "vbox4";
			this.vbox4.Spacing = 6;
			this.vbox4.BorderWidth = ((uint)(8));
			// Container child vbox4.Gtk.Box+BoxChild
			this.hbox3 = new global::Gtk.HBox ();
			this.hbox3.Name = "hbox3";
			this.hbox3.Spacing = 6;
			// Container child hbox3.Gtk.Box+BoxChild
			this.lblPieceID = new global::Gtk.Label ();
			this.lblPieceID.Name = "lblPieceID";
			this.lblPieceID.LabelProp = global::Mono.Unix.Catalog.GetString ("Piece ID :");
			this.hbox3.Add (this.lblPieceID);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.lblPieceID]));
			w8.Position = 0;
			w8.Expand = false;
			w8.Fill = false;
			// Container child hbox3.Gtk.Box+BoxChild
			this.txtPieceID = new global::Gtk.Entry ();
			this.txtPieceID.CanFocus = true;
			this.txtPieceID.Name = "txtPieceID";
			this.txtPieceID.IsEditable = true;
			this.txtPieceID.WidthChars = 3;
			this.txtPieceID.MaxLength = 3;
			this.txtPieceID.InvisibleChar = '●';
			this.hbox3.Add (this.txtPieceID);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.txtPieceID]));
			w9.Position = 1;
			// Container child hbox3.Gtk.Box+BoxChild
			this.btnGenID = new global::Gtk.Button ();
			this.btnGenID.CanFocus = true;
			this.btnGenID.Name = "btnGenID";
			this.btnGenID.UseUnderline = true;
			// Container child btnGenID.Gtk.Container+ContainerChild
			global::Gtk.Alignment w10 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w11 = new global::Gtk.HBox ();
			w11.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w12 = new global::Gtk.Image ();
			w12.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-execute", global::Gtk.IconSize.Menu);
			w11.Add (w12);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w14 = new global::Gtk.Label ();
			w14.LabelProp = global::Mono.Unix.Catalog.GetString ("Generate ID");
			w14.UseUnderline = true;
			w11.Add (w14);
			w10.Add (w11);
			this.btnGenID.Add (w10);
			this.hbox3.Add (this.btnGenID);
			global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.btnGenID]));
			w18.Position = 2;
			w18.Expand = false;
			w18.Fill = false;
			this.vbox4.Add (this.hbox3);
			global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.hbox3]));
			w19.Position = 0;
			w19.Expand = false;
			w19.Fill = false;
			// Container child vbox4.Gtk.Box+BoxChild
			this.hbox4 = new global::Gtk.HBox ();
			this.hbox4.Name = "hbox4";
			this.hbox4.Spacing = 6;
			// Container child hbox4.Gtk.Box+BoxChild
			this.lblPieceTitle = new global::Gtk.Label ();
			this.lblPieceTitle.Name = "lblPieceTitle";
			this.lblPieceTitle.LabelProp = global::Mono.Unix.Catalog.GetString ("Piece Title :");
			this.hbox4.Add (this.lblPieceTitle);
			global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.lblPieceTitle]));
			w20.Position = 0;
			w20.Expand = false;
			w20.Fill = false;
			// Container child hbox4.Gtk.Box+BoxChild
			this.txtPieceTitle = new global::Gtk.Entry ();
			this.txtPieceTitle.CanFocus = true;
			this.txtPieceTitle.Name = "txtPieceTitle";
			this.txtPieceTitle.IsEditable = true;
			this.txtPieceTitle.InvisibleChar = '●';
			this.hbox4.Add (this.txtPieceTitle);
			global::Gtk.Box.BoxChild w21 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.txtPieceTitle]));
			w21.Position = 1;
			this.vbox4.Add (this.hbox4);
			global::Gtk.Box.BoxChild w22 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.hbox4]));
			w22.Position = 1;
			w22.Expand = false;
			w22.Fill = false;
			// Container child vbox4.Gtk.Box+BoxChild
			this.hbox5 = new global::Gtk.HBox ();
			this.hbox5.Name = "hbox5";
			this.hbox5.Spacing = 6;
			// Container child hbox5.Gtk.Box+BoxChild
			this.lblPieceMinimumBid = new global::Gtk.Label ();
			this.lblPieceMinimumBid.Name = "lblPieceMinimumBid";
			this.lblPieceMinimumBid.LabelProp = global::Mono.Unix.Catalog.GetString ("Minimum Bid :");
			this.hbox5.Add (this.lblPieceMinimumBid);
			global::Gtk.Box.BoxChild w23 = ((global::Gtk.Box.BoxChild)(this.hbox5 [this.lblPieceMinimumBid]));
			w23.Position = 0;
			w23.Expand = false;
			w23.Fill = false;
			// Container child hbox5.Gtk.Box+BoxChild
			this.txtPieceMinimumBid = new global::Gtk.Entry ();
			this.txtPieceMinimumBid.CanFocus = true;
			this.txtPieceMinimumBid.Name = "txtPieceMinimumBid";
			this.txtPieceMinimumBid.IsEditable = true;
			this.txtPieceMinimumBid.InvisibleChar = '●';
			this.hbox5.Add (this.txtPieceMinimumBid);
			global::Gtk.Box.BoxChild w24 = ((global::Gtk.Box.BoxChild)(this.hbox5 [this.txtPieceMinimumBid]));
			w24.Position = 1;
			this.vbox4.Add (this.hbox5);
			global::Gtk.Box.BoxChild w25 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.hbox5]));
			w25.Position = 2;
			w25.Expand = false;
			w25.Fill = false;
			// Container child vbox4.Gtk.Box+BoxChild
			this.chkAAMB = new global::Gtk.CheckButton ();
			this.chkAAMB.CanFocus = true;
			this.chkAAMB.Name = "chkAAMB";
			this.chkAAMB.Label = global::Mono.Unix.Catalog.GetString ("After Auction at Min Bid?");
			this.chkAAMB.DrawIndicator = true;
			this.chkAAMB.UseUnderline = true;
			this.vbox4.Add (this.chkAAMB);
			global::Gtk.Box.BoxChild w26 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.chkAAMB]));
			w26.Position = 3;
			w26.Expand = false;
			w26.Fill = false;
			// Container child vbox4.Gtk.Box+BoxChild
			this.hbox6 = new global::Gtk.HBox ();
			this.hbox6.Name = "hbox6";
			this.hbox6.Spacing = 6;
			// Container child hbox6.Gtk.Box+BoxChild
			this.lblQuickSale = new global::Gtk.Label ();
			this.lblQuickSale.Name = "lblQuickSale";
			this.lblQuickSale.LabelProp = global::Mono.Unix.Catalog.GetString ("Quick Sale Price :");
			this.hbox6.Add (this.lblQuickSale);
			global::Gtk.Box.BoxChild w27 = ((global::Gtk.Box.BoxChild)(this.hbox6 [this.lblQuickSale]));
			w27.Position = 0;
			w27.Expand = false;
			w27.Fill = false;
			// Container child hbox6.Gtk.Box+BoxChild
			this.txtQuickSale = new global::Gtk.Entry ();
			this.txtQuickSale.CanFocus = true;
			this.txtQuickSale.Name = "txtQuickSale";
			this.txtQuickSale.IsEditable = true;
			this.txtQuickSale.InvisibleChar = '●';
			this.hbox6.Add (this.txtQuickSale);
			global::Gtk.Box.BoxChild w28 = ((global::Gtk.Box.BoxChild)(this.hbox6 [this.txtQuickSale]));
			w28.Position = 1;
			this.vbox4.Add (this.hbox6);
			global::Gtk.Box.BoxChild w29 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.hbox6]));
			w29.Position = 4;
			w29.Expand = false;
			w29.Fill = false;
			// Container child vbox4.Gtk.Box+BoxChild
			this.hbox7 = new global::Gtk.HBox ();
			this.hbox7.Name = "hbox7";
			this.hbox7.Spacing = 6;
			// Container child hbox7.Gtk.Box+BoxChild
			this.lblMedium = new global::Gtk.Label ();
			this.lblMedium.Name = "lblMedium";
			this.lblMedium.LabelProp = global::Mono.Unix.Catalog.GetString ("Medium :");
			this.hbox7.Add (this.lblMedium);
			global::Gtk.Box.BoxChild w30 = ((global::Gtk.Box.BoxChild)(this.hbox7 [this.lblMedium]));
			w30.Position = 0;
			w30.Expand = false;
			w30.Fill = false;
			// Container child hbox7.Gtk.Box+BoxChild
			this.txtMedium = new global::Gtk.Entry ();
			this.txtMedium.CanFocus = true;
			this.txtMedium.Name = "txtMedium";
			this.txtMedium.IsEditable = true;
			this.txtMedium.InvisibleChar = '●';
			this.hbox7.Add (this.txtMedium);
			global::Gtk.Box.BoxChild w31 = ((global::Gtk.Box.BoxChild)(this.hbox7 [this.txtMedium]));
			w31.Position = 1;
			this.vbox4.Add (this.hbox7);
			global::Gtk.Box.BoxChild w32 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.hbox7]));
			w32.Position = 5;
			w32.Expand = false;
			w32.Fill = false;
			// Container child vbox4.Gtk.Box+BoxChild
			this.table2 = new global::Gtk.Table (((uint)(2)), ((uint)(2)), false);
			this.table2.Name = "table2";
			this.table2.RowSpacing = ((uint)(6));
			this.table2.ColumnSpacing = ((uint)(6));
			// Container child table2.Gtk.Table+TableChild
			this.btnAdd = new global::Gtk.Button ();
			this.btnAdd.CanFocus = true;
			this.btnAdd.Name = "btnAdd";
			this.btnAdd.UseUnderline = true;
			// Container child btnAdd.Gtk.Container+ContainerChild
			global::Gtk.Alignment w33 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w34 = new global::Gtk.HBox ();
			w34.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w35 = new global::Gtk.Image ();
			w35.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-add", global::Gtk.IconSize.Menu);
			w34.Add (w35);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w37 = new global::Gtk.Label ();
			w37.LabelProp = global::Mono.Unix.Catalog.GetString ("Add");
			w37.UseUnderline = true;
			w34.Add (w37);
			w33.Add (w34);
			this.btnAdd.Add (w33);
			this.table2.Add (this.btnAdd);
			global::Gtk.Table.TableChild w41 = ((global::Gtk.Table.TableChild)(this.table2 [this.btnAdd]));
			w41.LeftAttach = ((uint)(1));
			w41.RightAttach = ((uint)(2));
			w41.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.btnClear = new global::Gtk.Button ();
			this.btnClear.CanFocus = true;
			this.btnClear.Name = "btnClear";
			this.btnClear.UseUnderline = true;
			// Container child btnClear.Gtk.Container+ContainerChild
			global::Gtk.Alignment w42 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w43 = new global::Gtk.HBox ();
			w43.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w44 = new global::Gtk.Image ();
			w44.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-cancel", global::Gtk.IconSize.Menu);
			w43.Add (w44);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w46 = new global::Gtk.Label ();
			w46.LabelProp = global::Mono.Unix.Catalog.GetString ("Clear");
			w46.UseUnderline = true;
			w43.Add (w46);
			w42.Add (w43);
			this.btnClear.Add (w42);
			this.table2.Add (this.btnClear);
			global::Gtk.Table.TableChild w50 = ((global::Gtk.Table.TableChild)(this.table2 [this.btnClear]));
			w50.TopAttach = ((uint)(1));
			w50.BottomAttach = ((uint)(2));
			w50.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.btnDelete = new global::Gtk.Button ();
			this.btnDelete.CanFocus = true;
			this.btnDelete.Name = "btnDelete";
			this.btnDelete.UseUnderline = true;
			// Container child btnDelete.Gtk.Container+ContainerChild
			global::Gtk.Alignment w51 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w52 = new global::Gtk.HBox ();
			w52.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w53 = new global::Gtk.Image ();
			w53.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-delete", global::Gtk.IconSize.Menu);
			w52.Add (w53);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w55 = new global::Gtk.Label ();
			w55.LabelProp = global::Mono.Unix.Catalog.GetString ("Delete");
			w55.UseUnderline = true;
			w52.Add (w55);
			w51.Add (w52);
			this.btnDelete.Add (w51);
			this.table2.Add (this.btnDelete);
			global::Gtk.Table.TableChild w59 = ((global::Gtk.Table.TableChild)(this.table2 [this.btnDelete]));
			w59.TopAttach = ((uint)(1));
			w59.BottomAttach = ((uint)(2));
			w59.LeftAttach = ((uint)(1));
			w59.RightAttach = ((uint)(2));
			w59.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.btnUpdate = new global::Gtk.Button ();
			this.btnUpdate.CanFocus = true;
			this.btnUpdate.Name = "btnUpdate";
			this.btnUpdate.UseUnderline = true;
			// Container child btnUpdate.Gtk.Container+ContainerChild
			global::Gtk.Alignment w60 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w61 = new global::Gtk.HBox ();
			w61.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w62 = new global::Gtk.Image ();
			w62.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-apply", global::Gtk.IconSize.Menu);
			w61.Add (w62);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w64 = new global::Gtk.Label ();
			w64.LabelProp = global::Mono.Unix.Catalog.GetString ("Update");
			w64.UseUnderline = true;
			w61.Add (w64);
			w60.Add (w61);
			this.btnUpdate.Add (w60);
			this.table2.Add (this.btnUpdate);
			global::Gtk.Table.TableChild w68 = ((global::Gtk.Table.TableChild)(this.table2 [this.btnUpdate]));
			w68.YOptions = ((global::Gtk.AttachOptions)(4));
			this.vbox4.Add (this.table2);
			global::Gtk.Box.BoxChild w69 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.table2]));
			w69.Position = 6;
			w69.Expand = false;
			w69.Fill = false;
			// Container child vbox4.Gtk.Box+BoxChild
			this.btnCreateSheet = new global::Gtk.Button ();
			this.btnCreateSheet.CanFocus = true;
			this.btnCreateSheet.Name = "btnCreateSheet";
			this.btnCreateSheet.UseUnderline = true;
			// Container child btnCreateSheet.Gtk.Container+ContainerChild
			global::Gtk.Alignment w70 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w71 = new global::Gtk.HBox ();
			w71.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w72 = new global::Gtk.Image ();
			w72.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-execute", global::Gtk.IconSize.Menu);
			w71.Add (w72);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w74 = new global::Gtk.Label ();
			w74.LabelProp = global::Mono.Unix.Catalog.GetString ("Create Bid Sheet");
			w74.UseUnderline = true;
			w71.Add (w74);
			w70.Add (w71);
			this.btnCreateSheet.Add (w70);
			this.vbox4.Add (this.btnCreateSheet);
			global::Gtk.Box.BoxChild w78 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.btnCreateSheet]));
			w78.Position = 7;
			w78.Expand = false;
			w78.Fill = false;
			this.GtkAlignment.Add (this.vbox4);
			this.frame1.Add (this.GtkAlignment);
			this.lblPieceInfo = new global::Gtk.Label ();
			this.lblPieceInfo.Name = "lblPieceInfo";
			this.lblPieceInfo.LabelProp = global::Mono.Unix.Catalog.GetString ("Piece Info:");
			this.lblPieceInfo.UseMarkup = true;
			this.frame1.LabelWidget = this.lblPieceInfo;
			this.vbox3.Add (this.frame1);
			global::Gtk.Box.BoxChild w81 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.frame1]));
			w81.Position = 1;
			w81.Expand = false;
			w81.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.btnGenCS = new global::Gtk.Button ();
			this.btnGenCS.CanFocus = true;
			this.btnGenCS.Name = "btnGenCS";
			this.btnGenCS.UseUnderline = true;
			// Container child btnGenCS.Gtk.Container+ContainerChild
			global::Gtk.Alignment w82 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w83 = new global::Gtk.HBox ();
			w83.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w84 = new global::Gtk.Image ();
			w84.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-execute", global::Gtk.IconSize.Menu);
			w83.Add (w84);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w86 = new global::Gtk.Label ();
			w86.LabelProp = global::Mono.Unix.Catalog.GetString ("Generate Control Sheet");
			w86.UseUnderline = true;
			w83.Add (w86);
			w82.Add (w83);
			this.btnGenCS.Add (w82);
			this.vbox3.Add (this.btnGenCS);
			global::Gtk.Box.BoxChild w90 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.btnGenCS]));
			w90.Position = 2;
			w90.Expand = false;
			w90.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.btnCancel = new global::Gtk.Button ();
			this.btnCancel.CanFocus = true;
			this.btnCancel.Name = "btnCancel";
			this.btnCancel.UseUnderline = true;
			// Container child btnCancel.Gtk.Container+ContainerChild
			global::Gtk.Alignment w91 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w92 = new global::Gtk.HBox ();
			w92.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w93 = new global::Gtk.Image ();
			w93.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-close", global::Gtk.IconSize.Menu);
			w92.Add (w93);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w95 = new global::Gtk.Label ();
			w95.LabelProp = global::Mono.Unix.Catalog.GetString ("Cancel");
			w95.UseUnderline = true;
			w92.Add (w95);
			w91.Add (w92);
			this.btnCancel.Add (w91);
			this.vbox3.Add (this.btnCancel);
			global::Gtk.Box.BoxChild w99 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.btnCancel]));
			w99.Position = 3;
			w99.Expand = false;
			w99.Fill = false;
			this.hbox2.Add (this.vbox3);
			global::Gtk.Box.BoxChild w100 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.vbox3]));
			w100.Position = 1;
			w100.Expand = false;
			w100.Fill = false;
			w100.Padding = ((uint)(8));
			this.Add (this.hbox2);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 419;
			this.DefaultHeight = 539;
			this.Show ();
			this.btnGenID.Clicked += new global::System.EventHandler (this.OnBtnGenIDClicked);
			this.btnUpdate.Clicked += new global::System.EventHandler (this.OnBtnUpdateClicked);
			this.btnDelete.Clicked += new global::System.EventHandler (this.OnBtnDeleteClicked);
			this.btnClear.Clicked += new global::System.EventHandler (this.OnBtnClearClicked);
			this.btnAdd.Clicked += new global::System.EventHandler (this.OnBtnAddClicked);
			this.btnCreateSheet.Clicked += new global::System.EventHandler (this.OnBtnCreateSheetClicked);
			this.btnGenCS.Clicked += new global::System.EventHandler (this.OnBtnGenCSClicked);
			this.btnCancel.Clicked += new global::System.EventHandler (this.OnBtnCancelClicked);
		}
	}
}
