
// This file has been generated by the GUI designer. Do not modify.
namespace Momiji
{
	public partial class frmLogin
	{
		private global::Gtk.VBox vbox1;
		
		private global::Gtk.Table table1;
		
		private global::Gtk.Button btnLogin;
		
		private global::Gtk.Label label1;
		
		private global::Gtk.Label label2;
		
		private global::Gtk.Entry txtPassword;
		
		private global::Gtk.Entry txtUsername;
		
		private global::Gtk.HBox hbox5;
		
		private global::Gtk.Button btnRetry;
		
		private global::Gtk.Label lblConnStatusLabel;
		
		private global::Gtk.ScrolledWindow GtkScrolledWindow;
		
		private global::Gtk.Label lblConnStatus;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget Momiji.frmLogin
			this.Name = "Momiji.frmLogin";
			this.Title = global::Mono.Unix.Catalog.GetString ("Welcome to Gallery Momiji");
			this.Icon = global::Gdk.Pixbuf.LoadFromResource ("Momiji.Resources.Crystal-Star-256.ico");
			this.WindowPosition = ((global::Gtk.WindowPosition)(3));
			this.Resizable = false;
			this.AllowGrow = false;
			this.DefaultWidth = 432;
			this.DefaultHeight = 103;
			// Container child Momiji.frmLogin.Gtk.Container+ContainerChild
			this.vbox1 = new global::Gtk.VBox ();
			this.vbox1.Spacing = 8;
			this.vbox1.BorderWidth = ((uint)(8));
			// Container child vbox1.Gtk.Box+BoxChild
			this.table1 = new global::Gtk.Table (((uint)(2)), ((uint)(3)), false);
			this.table1.Name = "table1";
			this.table1.RowSpacing = ((uint)(6));
			this.table1.ColumnSpacing = ((uint)(6));
			// Container child table1.Gtk.Table+TableChild
			this.btnLogin = new global::Gtk.Button ();
			this.btnLogin.WidthRequest = 96;
			this.btnLogin.CanFocus = true;
			this.btnLogin.Name = "btnLogin";
			this.btnLogin.UseUnderline = true;
			this.btnLogin.Label = global::Mono.Unix.Catalog.GetString ("Login");
			this.table1.Add (this.btnLogin);
			global::Gtk.Table.TableChild w1 = ((global::Gtk.Table.TableChild)(this.table1 [this.btnLogin]));
			w1.TopAttach = ((uint)(1));
			w1.BottomAttach = ((uint)(2));
			w1.LeftAttach = ((uint)(2));
			w1.RightAttach = ((uint)(3));
			w1.XOptions = ((global::Gtk.AttachOptions)(4));
			w1.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.label1 = new global::Gtk.Label ();
			this.label1.Name = "label1";
			this.label1.Xalign = 0F;
			this.label1.LabelProp = global::Mono.Unix.Catalog.GetString ("Username :");
			this.table1.Add (this.label1);
			global::Gtk.Table.TableChild w2 = ((global::Gtk.Table.TableChild)(this.table1 [this.label1]));
			w2.XOptions = ((global::Gtk.AttachOptions)(4));
			w2.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.label2 = new global::Gtk.Label ();
			this.label2.Name = "label2";
			this.label2.Xalign = 0F;
			this.label2.LabelProp = global::Mono.Unix.Catalog.GetString ("Password :");
			this.table1.Add (this.label2);
			global::Gtk.Table.TableChild w3 = ((global::Gtk.Table.TableChild)(this.table1 [this.label2]));
			w3.LeftAttach = ((uint)(1));
			w3.RightAttach = ((uint)(2));
			w3.XOptions = ((global::Gtk.AttachOptions)(4));
			w3.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.txtPassword = new global::Gtk.Entry ();
			this.txtPassword.WidthRequest = 200;
			this.txtPassword.CanFocus = true;
			this.txtPassword.Name = "txtPassword";
			this.txtPassword.IsEditable = true;
			this.txtPassword.Visibility = false;
			this.txtPassword.InvisibleChar = '●';
			this.table1.Add (this.txtPassword);
			global::Gtk.Table.TableChild w4 = ((global::Gtk.Table.TableChild)(this.table1 [this.txtPassword]));
			w4.TopAttach = ((uint)(1));
			w4.BottomAttach = ((uint)(2));
			w4.LeftAttach = ((uint)(1));
			w4.RightAttach = ((uint)(2));
			w4.XOptions = ((global::Gtk.AttachOptions)(4));
			w4.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.txtUsername = new global::Gtk.Entry ();
			this.txtUsername.WidthRequest = 200;
			this.txtUsername.CanFocus = true;
			this.txtUsername.Name = "txtUsername";
			this.txtUsername.IsEditable = true;
			this.txtUsername.InvisibleChar = '●';
			this.table1.Add (this.txtUsername);
			global::Gtk.Table.TableChild w5 = ((global::Gtk.Table.TableChild)(this.table1 [this.txtUsername]));
			w5.TopAttach = ((uint)(1));
			w5.BottomAttach = ((uint)(2));
			w5.XOptions = ((global::Gtk.AttachOptions)(4));
			w5.YOptions = ((global::Gtk.AttachOptions)(4));
			this.vbox1.Add (this.table1);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.table1]));
			w6.Position = 0;
			w6.Expand = false;
			w6.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox5 = new global::Gtk.HBox ();
			this.hbox5.Name = "hbox5";
			this.hbox5.Spacing = 6;
			// Container child hbox5.Gtk.Box+BoxChild
			this.btnRetry = new global::Gtk.Button ();
			this.btnRetry.WidthRequest = 64;
			this.btnRetry.CanFocus = true;
			this.btnRetry.Name = "btnRetry";
			this.btnRetry.UseUnderline = true;
			this.btnRetry.Label = global::Mono.Unix.Catalog.GetString ("Retry");
			this.hbox5.Add (this.btnRetry);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox5 [this.btnRetry]));
			w7.Position = 0;
			w7.Expand = false;
			w7.Fill = false;
			// Container child hbox5.Gtk.Box+BoxChild
			this.lblConnStatusLabel = new global::Gtk.Label ();
			this.lblConnStatusLabel.Name = "lblConnStatusLabel";
			this.lblConnStatusLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("MySQL Status :");
			this.hbox5.Add (this.lblConnStatusLabel);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hbox5 [this.lblConnStatusLabel]));
			w8.Position = 1;
			w8.Expand = false;
			w8.Fill = false;
			// Container child hbox5.Gtk.Box+BoxChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			global::Gtk.Viewport w9 = new global::Gtk.Viewport ();
			w9.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child GtkViewport.Gtk.Container+ContainerChild
			this.lblConnStatus = new global::Gtk.Label ();
			this.lblConnStatus.Name = "lblConnStatus";
			this.lblConnStatus.Xalign = 0F;
			this.lblConnStatus.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Connecting...</b>");
			this.lblConnStatus.UseMarkup = true;
			w9.Add (this.lblConnStatus);
			this.GtkScrolledWindow.Add (w9);
			this.hbox5.Add (this.GtkScrolledWindow);
			global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.hbox5 [this.GtkScrolledWindow]));
			w12.Position = 2;
			this.vbox1.Add (this.hbox5);
			global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox5]));
			w13.Position = 1;
			w13.Expand = false;
			w13.Fill = false;
			w13.Padding = ((uint)(8));
			this.Add (this.vbox1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Show ();
			this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
			this.txtUsername.Activated += new global::System.EventHandler (this.OnTxtUsernameActivated);
			this.txtPassword.Activated += new global::System.EventHandler (this.OnTxtPasswordActivated);
			this.btnLogin.Clicked += new global::System.EventHandler (this.OnBtnLoginClicked);
			this.btnRetry.Clicked += new global::System.EventHandler (this.OnBtnRetryClicked);
		}
	}
}
